//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ammotypelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ammotypelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="missile"/&gt;
 *     &lt;enumeration value="countermeasure"/&gt;
 *     &lt;enumeration value="deployable"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ammotypelookup")
@XmlEnum
public enum Ammotypelookup {

    @XmlEnumValue("missile")
    MISSILE("missile"),
    @XmlEnumValue("countermeasure")
    COUNTERMEASURE("countermeasure"),
    @XmlEnumValue("deployable")
    DEPLOYABLE("deployable");
    private final String value;

    Ammotypelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Ammotypelookup fromValue(String v) {
        for (Ammotypelookup c: Ammotypelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
