//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="character"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="category" type="{}characterdbcategory" minOccurs="0"/&gt;
 *                   &lt;group ref="{}createnpc"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attGroup ref="{}createnpc"/&gt;
 *                 &lt;attribute name="id" use="required" type="{}idname" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "character"
})
@XmlRootElement(name = "characters")
public class Characters {

    protected List<Characters.Character> character;

    /**
     * Gets the value of the character property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the character property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Characters.Character }
     * 
     * 
     */
    public List<Characters.Character> getCharacter() {
        if (character == null) {
            character = new ArrayList<Characters.Character>();
        }
        return this.character;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="category" type="{}characterdbcategory" minOccurs="0"/&gt;
     *         &lt;group ref="{}createnpc"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attGroup ref="{}createnpc"/&gt;
     *       &lt;attribute name="id" use="required" type="{}idname" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "select",
        "nameOrOwnerOrPage"
    })
    public static class Character {

        protected Characterdbcategory category;
        protected Characterdbcategoryselect select;
        @XmlElements({
            @XmlElement(name = "name", type = be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Name.class),
            @XmlElement(name = "owner", type = Selectrandom.class),
            @XmlElement(name = "page", type = be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Page.class),
            @XmlElement(name = "skills", type = be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Skills.class),
            @XmlElement(name = "stock", type = be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Stock.class),
            @XmlElement(name = "clothing", type = be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Clothing.class)
        })
        protected List<Object> nameOrOwnerOrPage;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "name")
        @XmlSchemaType(name = "anySimpleType")
        protected String name;
        @XmlAttribute(name = "description")
        @XmlSchemaType(name = "anySimpleType")
        protected String description;
        @XmlAttribute(name = "macro")
        protected String macro;
        @XmlAttribute(name = "group")
        protected String group;
        @XmlAttribute(name = "actor")
        protected String actor;
        @XmlAttribute(name = "ref")
        protected String ref;

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link Characterdbcategory }
         *     
         */
        public Characterdbcategory getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link Characterdbcategory }
         *     
         */
        public void setCategory(Characterdbcategory value) {
            this.category = value;
        }

        /**
         * Gets the value of the select property.
         * 
         * @return
         *     possible object is
         *     {@link Characterdbcategoryselect }
         *     
         */
        public Characterdbcategoryselect getSelect() {
            return select;
        }

        /**
         * Sets the value of the select property.
         * 
         * @param value
         *     allowed object is
         *     {@link Characterdbcategoryselect }
         *     
         */
        public void setSelect(Characterdbcategoryselect value) {
            this.select = value;
        }

        /**
         * Gets the value of the nameOrOwnerOrPage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nameOrOwnerOrPage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNameOrOwnerOrPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Name }
         * {@link Selectrandom }
         * {@link be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Page }
         * {@link be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Skills }
         * {@link be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Stock }
         * {@link be.celludriel.universegenerator.model.xml.libraries.Jobs.Job.Masstraffic.People.Person.Clothing }
         * 
         * 
         */
        public List<Object> getNameOrOwnerOrPage() {
            if (nameOrOwnerOrPage == null) {
                nameOrOwnerOrPage = new ArrayList<Object>();
            }
            return this.nameOrOwnerOrPage;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the macro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMacro() {
            return macro;
        }

        /**
         * Sets the value of the macro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMacro(String value) {
            this.macro = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroup(String value) {
            this.group = value;
        }

        /**
         * Gets the value of the actor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActor() {
            return actor;
        }

        /**
         * Sets the value of the actor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActor(String value) {
            this.actor = value;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }

    }

}
