//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for componentstatelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="componentstatelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="construction"/&gt;
 *     &lt;enumeration value="operational"/&gt;
 *     &lt;enumeration value="wreck"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "componentstatelookup")
@XmlEnum
public enum Componentstatelookup {

    @XmlEnumValue("construction")
    CONSTRUCTION("construction"),
    @XmlEnumValue("operational")
    OPERATIONAL("operational"),
    @XmlEnumValue("wreck")
    WRECK("wreck");
    private final String value;

    Componentstatelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Componentstatelookup fromValue(String v) {
        for (Componentstatelookup c: Componentstatelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
