//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for encountertypelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="encountertypelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="destruction"/&gt;
 *     &lt;enumeration value="damage"/&gt;
 *     &lt;enumeration value="loot"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "encountertypelookup")
@XmlEnum
public enum Encountertypelookup {


    /**
     * 
     *             Object has been destroyed.
     *           
     * 
     */
    @XmlEnumValue("destruction")
    DESTRUCTION("destruction"),

    /**
     * 
     *             Object has been damaged. Param = string describing the severity: low, medium, high
     *           
     * 
     */
    @XmlEnumValue("damage")
    DAMAGE("damage"),

    /**
     * 
     *             Object has acquired loot. Param = string describing the value: low, medium, high
     *           
     * 
     */
    @XmlEnumValue("loot")
    LOOT("loot");
    private final String value;

    Encountertypelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Encountertypelookup fromValue(String v) {
        for (Encountertypelookup c: Encountertypelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
