//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entityhirablerolelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="entityhirablerolelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="service"/&gt;
 *     &lt;enumeration value="marine"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "entityhirablerolelookup")
@XmlEnum
public enum Entityhirablerolelookup {

    @XmlEnumValue("service")
    SERVICE("service"),
    @XmlEnumValue("marine")
    MARINE("marine");
    private final String value;

    Entityhirablerolelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Entityhirablerolelookup fromValue(String v) {
        for (Entityhirablerolelookup c: Entityhirablerolelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
