//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for factionlookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="factionlookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="alliance"/&gt;
 *     &lt;enumeration value="antigone"/&gt;
 *     &lt;enumeration value="argon"/&gt;
 *     &lt;enumeration value="buccaneers"/&gt;
 *     &lt;enumeration value="court"/&gt;
 *     &lt;enumeration value="civilian"/&gt;
 *     &lt;enumeration value="criminal"/&gt;
 *     &lt;enumeration value="freesplit"/&gt;
 *     &lt;enumeration value="hatikvah"/&gt;
 *     &lt;enumeration value="holyorder"/&gt;
 *     &lt;enumeration value="khaak"/&gt;
 *     &lt;enumeration value="ministry"/&gt;
 *     &lt;enumeration value="ownerless"/&gt;
 *     &lt;enumeration value="paranid"/&gt;
 *     &lt;enumeration value="pioneers"/&gt;
 *     &lt;enumeration value="player"/&gt;
 *     &lt;enumeration value="scaleplate"/&gt;
 *     &lt;enumeration value="smuggler"/&gt;
 *     &lt;enumeration value="split"/&gt;
 *     &lt;enumeration value="teladi"/&gt;
 *     &lt;enumeration value="terran"/&gt;
 *     &lt;enumeration value="trinity"/&gt;
 *     &lt;enumeration value="yaki"/&gt;
 *     &lt;enumeration value="xenon"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "factionlookup")
@XmlEnum
public enum Factionlookup {


    /**
     * 
     *             Alliance of the Word
     *           
     * 
     */
    @XmlEnumValue("alliance")
    ALLIANCE("alliance"),

    /**
     * 
     *             Antigone Republic
     *           
     * 
     */
    @XmlEnumValue("antigone")
    ANTIGONE("antigone"),

    /**
     * 
     *             Argon Federation
     *           
     * 
     */
    @XmlEnumValue("argon")
    ARGON("argon"),

    /**
     * 
     *             Duke's Buccaneers
     *           
     * 
     */
    @XmlEnumValue("buccaneers")
    BUCCANEERS("buccaneers"),

    /**
     * 
     *             Court of Curbs (only valid if Split Vendetta extension is active)
     *           
     * 
     */
    @XmlEnumValue("court")
    COURT("court"),

    /**
     * 
     *             Civilian
     *           
     * 
     */
    @XmlEnumValue("civilian")
    CIVILIAN("civilian"),

    /**
     * 
     *             Criminal
     *           
     * 
     */
    @XmlEnumValue("criminal")
    CRIMINAL("criminal"),

    /**
     * 
     *             Free Families (only valid if Split Vendetta extension is active)
     *           
     * 
     */
    @XmlEnumValue("freesplit")
    FREESPLIT("freesplit"),

    /**
     * 
     *             Hatikvah Free League
     *           
     * 
     */
    @XmlEnumValue("hatikvah")
    HATIKVAH("hatikvah"),

    /**
     * 
     *             Holy Order of the Pontifex
     *           
     * 
     */
    @XmlEnumValue("holyorder")
    HOLYORDER("holyorder"),

    /**
     * 
     *             Kha'ak
     *           
     * 
     */
    @XmlEnumValue("khaak")
    KHAAK("khaak"),

    /**
     * 
     *             Ministry of Finance
     *           
     * 
     */
    @XmlEnumValue("ministry")
    MINISTRY("ministry"),

    /**
     * 
     *             Ownerless
     *           
     * 
     */
    @XmlEnumValue("ownerless")
    OWNERLESS("ownerless"),

    /**
     * 
     *             Paranid
     *           
     * 
     */
    @XmlEnumValue("paranid")
    PARANID("paranid"),

    /**
     * 
     *             Pioneers (only valid if Terran extension is active)
     *           
     * 
     */
    @XmlEnumValue("pioneers")
    PIONEERS("pioneers"),

    /**
     * 
     *             Player
     *           
     * 
     */
    @XmlEnumValue("player")
    PLAYER("player"),

    /**
     * 
     *             Scale Plate Pact
     *           
     * 
     */
    @XmlEnumValue("scaleplate")
    SCALEPLATE("scaleplate"),

    /**
     * 
     *             Smuggler
     *           
     * 
     */
    @XmlEnumValue("smuggler")
    SMUGGLER("smuggler"),

    /**
     * 
     *             Zyarth Patriarchy (only valid if Split Vendetta extension is active)
     *           
     * 
     */
    @XmlEnumValue("split")
    SPLIT("split"),

    /**
     * 
     *             Teladi Company
     *           
     * 
     */
    @XmlEnumValue("teladi")
    TELADI("teladi"),

    /**
     * 
     *             Terran main faction (only valid if Terran extension is active)
     *           
     * 
     */
    @XmlEnumValue("terran")
    TERRAN("terran"),

    /**
     * 
     *             Realm of the Trinity
     *           
     * 
     */
    @XmlEnumValue("trinity")
    TRINITY("trinity"),

    /**
     * 
     *             Yaki (only valid if Terran extension is active)
     *           
     * 
     */
    @XmlEnumValue("yaki")
    YAKI("yaki"),

    /**
     * 
     *             Xenon
     *           
     * 
     */
    @XmlEnumValue("xenon")
    XENON("xenon");
    private final String value;

    Factionlookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Factionlookup fromValue(String v) {
        for (Factionlookup c: Factionlookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
