//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infolibrarytypelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="infolibrarytypelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="shiptypes_xl"/&gt;
 *     &lt;enumeration value="shiptypes_l"/&gt;
 *     &lt;enumeration value="shiptypes_m"/&gt;
 *     &lt;enumeration value="shiptypes_s"/&gt;
 *     &lt;enumeration value="shiptypes_xs"/&gt;
 *     &lt;enumeration value="stationtypes"/&gt;
 *     &lt;enumeration value="moduletypes_production"/&gt;
 *     &lt;enumeration value="moduletypes_build"/&gt;
 *     &lt;enumeration value="moduletypes_storage"/&gt;
 *     &lt;enumeration value="moduletypes_habitation"/&gt;
 *     &lt;enumeration value="moduletypes_defence"/&gt;
 *     &lt;enumeration value="moduletypes_communication"/&gt;
 *     &lt;enumeration value="moduletypes_dock"/&gt;
 *     &lt;enumeration value="moduletypes_pier"/&gt;
 *     &lt;enumeration value="moduletypes_other"/&gt;
 *     &lt;enumeration value="moduletypes_venture"/&gt;
 *     &lt;enumeration value="weapons_lasers"/&gt;
 *     &lt;enumeration value="weapons_missilelaunchers"/&gt;
 *     &lt;enumeration value="weapons_turrets"/&gt;
 *     &lt;enumeration value="weapons_missileturrets"/&gt;
 *     &lt;enumeration value="shieldgentypes"/&gt;
 *     &lt;enumeration value="enginetypes"/&gt;
 *     &lt;enumeration value="thrustertypes"/&gt;
 *     &lt;enumeration value="missiletypes"/&gt;
 *     &lt;enumeration value="marines"/&gt;
 *     &lt;enumeration value="unique_npcs"/&gt;
 *     &lt;enumeration value="wares"/&gt;
 *     &lt;enumeration value="productionmethods"/&gt;
 *     &lt;enumeration value="researchmethods"/&gt;
 *     &lt;enumeration value="researchables"/&gt;
 *     &lt;enumeration value="inventory_wares"/&gt;
 *     &lt;enumeration value="races"/&gt;
 *     &lt;enumeration value="factions"/&gt;
 *     &lt;enumeration value="licences"/&gt;
 *     &lt;enumeration value="entitytypes"/&gt;
 *     &lt;enumeration value="equipmentmods"/&gt;
 *     &lt;enumeration value="paintmods"/&gt;
 *     &lt;enumeration value="clothingmods"/&gt;
 *     &lt;enumeration value="software"/&gt;
 *     &lt;enumeration value="bombs"/&gt;
 *     &lt;enumeration value="lasertowers"/&gt;
 *     &lt;enumeration value="mines"/&gt;
 *     &lt;enumeration value="navbeacons"/&gt;
 *     &lt;enumeration value="resourceprobes"/&gt;
 *     &lt;enumeration value="satellites"/&gt;
 *     &lt;enumeration value="timeline"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "infolibrarytypelookup")
@XmlEnum
public enum Infolibrarytypelookup {

    @XmlEnumValue("shiptypes_xl")
    SHIPTYPES_XL("shiptypes_xl"),
    @XmlEnumValue("shiptypes_l")
    SHIPTYPES_L("shiptypes_l"),
    @XmlEnumValue("shiptypes_m")
    SHIPTYPES_M("shiptypes_m"),
    @XmlEnumValue("shiptypes_s")
    SHIPTYPES_S("shiptypes_s"),
    @XmlEnumValue("shiptypes_xs")
    SHIPTYPES_XS("shiptypes_xs"),
    @XmlEnumValue("stationtypes")
    STATIONTYPES("stationtypes"),
    @XmlEnumValue("moduletypes_production")
    MODULETYPES_PRODUCTION("moduletypes_production"),
    @XmlEnumValue("moduletypes_build")
    MODULETYPES_BUILD("moduletypes_build"),
    @XmlEnumValue("moduletypes_storage")
    MODULETYPES_STORAGE("moduletypes_storage"),
    @XmlEnumValue("moduletypes_habitation")
    MODULETYPES_HABITATION("moduletypes_habitation"),
    @XmlEnumValue("moduletypes_defence")
    MODULETYPES_DEFENCE("moduletypes_defence"),
    @XmlEnumValue("moduletypes_communication")
    MODULETYPES_COMMUNICATION("moduletypes_communication"),
    @XmlEnumValue("moduletypes_dock")
    MODULETYPES_DOCK("moduletypes_dock"),
    @XmlEnumValue("moduletypes_pier")
    MODULETYPES_PIER("moduletypes_pier"),
    @XmlEnumValue("moduletypes_other")
    MODULETYPES_OTHER("moduletypes_other"),
    @XmlEnumValue("moduletypes_venture")
    MODULETYPES_VENTURE("moduletypes_venture"),
    @XmlEnumValue("weapons_lasers")
    WEAPONS_LASERS("weapons_lasers"),
    @XmlEnumValue("weapons_missilelaunchers")
    WEAPONS_MISSILELAUNCHERS("weapons_missilelaunchers"),
    @XmlEnumValue("weapons_turrets")
    WEAPONS_TURRETS("weapons_turrets"),
    @XmlEnumValue("weapons_missileturrets")
    WEAPONS_MISSILETURRETS("weapons_missileturrets"),
    @XmlEnumValue("shieldgentypes")
    SHIELDGENTYPES("shieldgentypes"),
    @XmlEnumValue("enginetypes")
    ENGINETYPES("enginetypes"),
    @XmlEnumValue("thrustertypes")
    THRUSTERTYPES("thrustertypes"),
    @XmlEnumValue("missiletypes")
    MISSILETYPES("missiletypes"),
    @XmlEnumValue("marines")
    MARINES("marines"),
    @XmlEnumValue("unique_npcs")
    UNIQUE_NPCS("unique_npcs"),
    @XmlEnumValue("wares")
    WARES("wares"),
    @XmlEnumValue("productionmethods")
    PRODUCTIONMETHODS("productionmethods"),
    @XmlEnumValue("researchmethods")
    RESEARCHMETHODS("researchmethods"),
    @XmlEnumValue("researchables")
    RESEARCHABLES("researchables"),
    @XmlEnumValue("inventory_wares")
    INVENTORY_WARES("inventory_wares"),
    @XmlEnumValue("races")
    RACES("races"),
    @XmlEnumValue("factions")
    FACTIONS("factions"),
    @XmlEnumValue("licences")
    LICENCES("licences"),
    @XmlEnumValue("entitytypes")
    ENTITYTYPES("entitytypes"),
    @XmlEnumValue("equipmentmods")
    EQUIPMENTMODS("equipmentmods"),
    @XmlEnumValue("paintmods")
    PAINTMODS("paintmods"),
    @XmlEnumValue("clothingmods")
    CLOTHINGMODS("clothingmods"),
    @XmlEnumValue("software")
    SOFTWARE("software"),
    @XmlEnumValue("bombs")
    BOMBS("bombs"),
    @XmlEnumValue("lasertowers")
    LASERTOWERS("lasertowers"),
    @XmlEnumValue("mines")
    MINES("mines"),
    @XmlEnumValue("navbeacons")
    NAVBEACONS("navbeacons"),
    @XmlEnumValue("resourceprobes")
    RESOURCEPROBES("resourceprobes"),
    @XmlEnumValue("satellites")
    SATELLITES("satellites"),
    @XmlEnumValue("timeline")
    TIMELINE("timeline");
    private final String value;

    Infolibrarytypelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Infolibrarytypelookup fromValue(String v) {
        for (Infolibrarytypelookup c: Infolibrarytypelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
