//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logcategorylookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="logcategorylookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="general"/&gt;
 *     &lt;enumeration value="missions"/&gt;
 *     &lt;enumeration value="news"/&gt;
 *     &lt;enumeration value="upkeep"/&gt;
 *     &lt;enumeration value="alerts"/&gt;
 *     &lt;enumeration value="tips"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "logcategorylookup")
@XmlEnum
public enum Logcategorylookup {

    @XmlEnumValue("general")
    GENERAL("general"),
    @XmlEnumValue("missions")
    MISSIONS("missions"),
    @XmlEnumValue("news")
    NEWS("news"),
    @XmlEnumValue("upkeep")
    UPKEEP("upkeep"),
    @XmlEnumValue("alerts")
    ALERTS("alerts"),
    @XmlEnumValue("tips")
    TIPS("tips");
    private final String value;

    Logcategorylookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Logcategorylookup fromValue(String v) {
        for (Logcategorylookup c: Logcategorylookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
