//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchtrade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchtrade"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="amount" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="offeramount" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{}rangefilter"&gt;
 *                 &lt;attribute name="tradepartner" type="{}container" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="price" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="relativeprice" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="stocklevel" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="totalprice" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="volume" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="totalvolume" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="mintotalvolume" type="{}rangefilter" minOccurs="0"/&gt;
 *         &lt;element name="match_buyer" type="{}matchbuyer" minOccurs="0"/&gt;
 *         &lt;element name="match_seller" type="{}matchseller" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="wares" type="{}ware" /&gt;
 *       &lt;attribute name="unbundle" type="{}booleanexpression" /&gt;
 *       &lt;attribute name="bundle" type="{}booleanexpression" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchtrade", propOrder = {

})
@XmlSeeAlso({
    Matchtradeoffer.class
})
public class Matchtrade {

    protected Rangefilter amount;
    protected Matchtrade.Offeramount offeramount;
    protected Rangefilter price;
    protected Rangefilter relativeprice;
    protected Rangefilter stocklevel;
    protected Rangefilter totalprice;
    protected Rangefilter volume;
    protected Rangefilter totalvolume;
    protected Rangefilter mintotalvolume;
    @XmlElement(name = "match_buyer")
    protected Matchbuyer matchBuyer;
    @XmlElement(name = "match_seller")
    protected Matchseller matchSeller;
    @XmlAttribute(name = "wares")
    protected String wares;
    @XmlAttribute(name = "unbundle")
    protected String unbundle;
    @XmlAttribute(name = "bundle")
    protected String bundle;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setAmount(Rangefilter value) {
        this.amount = value;
    }

    /**
     * Gets the value of the offeramount property.
     * 
     * @return
     *     possible object is
     *     {@link Matchtrade.Offeramount }
     *     
     */
    public Matchtrade.Offeramount getOfferamount() {
        return offeramount;
    }

    /**
     * Sets the value of the offeramount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Matchtrade.Offeramount }
     *     
     */
    public void setOfferamount(Matchtrade.Offeramount value) {
        this.offeramount = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setPrice(Rangefilter value) {
        this.price = value;
    }

    /**
     * Gets the value of the relativeprice property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getRelativeprice() {
        return relativeprice;
    }

    /**
     * Sets the value of the relativeprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setRelativeprice(Rangefilter value) {
        this.relativeprice = value;
    }

    /**
     * Gets the value of the stocklevel property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getStocklevel() {
        return stocklevel;
    }

    /**
     * Sets the value of the stocklevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setStocklevel(Rangefilter value) {
        this.stocklevel = value;
    }

    /**
     * Gets the value of the totalprice property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getTotalprice() {
        return totalprice;
    }

    /**
     * Sets the value of the totalprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setTotalprice(Rangefilter value) {
        this.totalprice = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setVolume(Rangefilter value) {
        this.volume = value;
    }

    /**
     * Gets the value of the totalvolume property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getTotalvolume() {
        return totalvolume;
    }

    /**
     * Sets the value of the totalvolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setTotalvolume(Rangefilter value) {
        this.totalvolume = value;
    }

    /**
     * Gets the value of the mintotalvolume property.
     * 
     * @return
     *     possible object is
     *     {@link Rangefilter }
     *     
     */
    public Rangefilter getMintotalvolume() {
        return mintotalvolume;
    }

    /**
     * Sets the value of the mintotalvolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rangefilter }
     *     
     */
    public void setMintotalvolume(Rangefilter value) {
        this.mintotalvolume = value;
    }

    /**
     * Gets the value of the matchBuyer property.
     * 
     * @return
     *     possible object is
     *     {@link Matchbuyer }
     *     
     */
    public Matchbuyer getMatchBuyer() {
        return matchBuyer;
    }

    /**
     * Sets the value of the matchBuyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Matchbuyer }
     *     
     */
    public void setMatchBuyer(Matchbuyer value) {
        this.matchBuyer = value;
    }

    /**
     * Gets the value of the matchSeller property.
     * 
     * @return
     *     possible object is
     *     {@link Matchseller }
     *     
     */
    public Matchseller getMatchSeller() {
        return matchSeller;
    }

    /**
     * Sets the value of the matchSeller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Matchseller }
     *     
     */
    public void setMatchSeller(Matchseller value) {
        this.matchSeller = value;
    }

    /**
     * Gets the value of the wares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWares() {
        return wares;
    }

    /**
     * Sets the value of the wares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWares(String value) {
        this.wares = value;
    }

    /**
     * Gets the value of the unbundle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnbundle() {
        return unbundle;
    }

    /**
     * Sets the value of the unbundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnbundle(String value) {
        this.unbundle = value;
    }

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundle(String value) {
        this.bundle = value;
    }


    /**
     * 
     *               Filter by the amount in the trade in addition to the amount reserved
     *             
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{}rangefilter"&gt;
     *       &lt;attribute name="tradepartner" type="{}container" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Offeramount
        extends Rangefilter
    {

        @XmlAttribute(name = "tradepartner")
        protected String tradepartner;

        /**
         * Gets the value of the tradepartner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTradepartner() {
            return tradepartner;
        }

        /**
         * Sets the value of the tradepartner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTradepartner(String value) {
            this.tradepartner = value;
        }

    }

}
