//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchsubfilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchsubfilter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}matchbase"&gt;
 *       &lt;attGroup ref="{}findarbitrary"/&gt;
 *       &lt;attribute name="negate" type="{}negatefilter" /&gt;
 *       &lt;attribute name="comment" type="{}comment" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchsubfilter")
public class Matchsubfilter
    extends Matchbase
{

    @XmlAttribute(name = "negate")
    protected Boolean negate;
    @XmlAttribute(name = "comment")
    protected String comment;
    @XmlAttribute(name = "class")
    protected List<String> clazz;
    @XmlAttribute(name = "exactclass")
    protected List<String> exactclass;
    @XmlAttribute(name = "restorable")
    protected String restorable;
    @XmlAttribute(name = "repairable")
    protected String repairable;
    @XmlAttribute(name = "needsrepair")
    protected String needsrepair;
    @XmlAttribute(name = "normalzone")
    protected String normalzone;
    @XmlAttribute(name = "tempzone")
    protected String tempzone;
    @XmlAttribute(name = "accessgrantedto")
    protected String accessgrantedto;
    @XmlAttribute(name = "accessrestrictedto")
    protected String accessrestrictedto;
    @XmlAttribute(name = "normalcluster")
    protected String normalcluster;
    @XmlAttribute(name = "docked")
    protected String docked;
    @XmlAttribute(name = "shiptype")
    protected String shiptype;
    @XmlAttribute(name = "hasjob")
    protected String hasjob;
    @XmlAttribute(name = "job")
    protected String job;
    @XmlAttribute(name = "validjobship")
    protected String validjobship;
    @XmlAttribute(name = "jobtags")
    protected String jobtags;
    @XmlAttribute(name = "encounterid")
    protected String encounterid;
    @XmlAttribute(name = "encountership")
    protected String encountership;
    @XmlAttribute(name = "contested")
    protected String contested;
    @XmlAttribute(name = "contestedby")
    protected String contestedby;
    @XmlAttribute(name = "macro")
    protected String macro;
    @XmlAttribute(name = "owner")
    protected String owner;
    @XmlAttribute(name = "trueowner")
    protected String trueowner;
    @XmlAttribute(name = "coverowner")
    protected String coverowner;
    @XmlAttribute(name = "policefaction")
    protected String policefaction;
    @XmlAttribute(name = "negateownerfilter")
    protected String negateownerfilter;
    @XmlAttribute(name = "tag")
    protected String tag;
    @XmlAttribute(name = "excluded")
    protected String excluded;
    @XmlAttribute(name = "grouptag")
    protected String grouptag;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "integrated")
    protected String integrated;
    @XmlAttribute(name = "invulnerable")
    protected String invulnerable;
    @XmlAttribute(name = "hullinvulnerable")
    protected String hullinvulnerable;
    @XmlAttribute(name = "shieldinvulnerable")
    protected String shieldinvulnerable;
    @XmlAttribute(name = "indestructible")
    protected String indestructible;
    @XmlAttribute(name = "checkoperational")
    protected String checkoperational;
    @XmlAttribute(name = "functional")
    protected String functional;
    @XmlAttribute(name = "surfaceelement")
    protected String surfaceelement;
    @XmlAttribute(name = "module")
    protected String module;
    @XmlAttribute(name = "known")
    protected String known;
    @XmlAttribute(name = "knownto")
    protected String knownto;
    @XmlAttribute(name = "suspicious")
    protected String suspicious;
    @XmlAttribute(name = "destination")
    protected String destination;
    @XmlAttribute(name = "hastradeoffer")
    protected String hastradeoffer;
    @XmlAttribute(name = "tradesknownto")
    protected String tradesknownto;
    @XmlAttribute(name = "canhaveofferlocation")
    protected String canhaveofferlocation;
    @XmlAttribute(name = "freemissionofferslot")
    protected String freemissionofferslot;
    @XmlAttribute(name = "freesignalleakslot")
    protected String freesignalleakslot;
    @XmlAttribute(name = "numfreeactorslots")
    protected String numfreeactorslots;
    @XmlAttribute(name = "freemissionactorslot")
    protected String freemissionactorslot;
    @XmlAttribute(name = "masstraffic")
    protected String masstraffic;
    @XmlAttribute(name = "onlineobject")
    protected String onlineobject;
    @XmlAttribute(name = "visitor")
    protected String visitor;
    @XmlAttribute(name = "walkable")
    protected String walkable;
    @XmlAttribute(name = "roompopulationtype")
    protected String roompopulationtype;
    @XmlAttribute(name = "building")
    protected String building;
    @XmlAttribute(name = "busy")
    protected String busy;
    @XmlAttribute(name = "hasbuildingtask")
    protected String hasbuildingtask;
    @XmlAttribute(name = "canbebuiltby")
    protected String canbebuiltby;
    @XmlAttribute(name = "canbebuiltbyany")
    protected String canbebuiltbyany;
    @XmlAttribute(name = "canbuildfor")
    protected String canbuildfor;
    @XmlAttribute(name = "canbuildclass")
    protected String canbuildclass;
    @XmlAttribute(name = "canbuildships")
    protected String canbuildships;
    @XmlAttribute(name = "canequipclass")
    protected String canequipclass;
    @XmlAttribute(name = "cansupplyclass")
    protected String cansupplyclass;
    @XmlAttribute(name = "canequipships")
    protected String canequipships;
    @XmlAttribute(name = "cansupplyships")
    protected String cansupplyships;
    @XmlAttribute(name = "canbuildequipment")
    protected String canbuildequipment;
    @XmlAttribute(name = "canbuildmacro")
    protected String canbuildmacro;
    @XmlAttribute(name = "waretransport")
    protected String waretransport;
    @XmlAttribute(name = "weaponmode")
    protected String weaponmode;
    @XmlAttribute(name = "weapontype")
    protected Weapontypelookup weapontype;
    @XmlAttribute(name = "primarypurpose")
    protected String primarypurpose;
    @XmlAttribute(name = "deployable")
    protected String deployable;
    @XmlAttribute(name = "datavault")
    protected String datavault;
    @XmlAttribute(name = "deployablecategory")
    protected String deployablecategory;
    @XmlAttribute(name = "mayattack")
    protected String mayattack;
    @XmlAttribute(name = "maybeattackedby")
    protected String maybeattackedby;
    @XmlAttribute(name = "ishostileto")
    protected String ishostileto;
    @XmlAttribute(name = "canbepickedup")
    protected String canbepickedup;
    @XmlAttribute(name = "commandeerable")
    protected String commandeerable;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "hascommander")
    protected String hascommander;
    @XmlAttribute(name = "hascontrolentity")
    protected String hascontrolentity;
    @XmlAttribute(name = "capturable")
    protected String capturable;
    @XmlAttribute(name = "accelerator")
    protected String accelerator;
    @XmlAttribute(name = "active")
    protected String active;
    @XmlAttribute(name = "paused")
    protected String paused;
    @XmlAttribute(name = "pausedmanually")
    protected String pausedmanually;
    @XmlAttribute(name = "signalleaktype")
    protected String signalleaktype;
    @XmlAttribute(name = "extension")
    protected String extension;
    @XmlAttribute(name = "personalextension")
    protected String personalextension;
    @XmlAttribute(name = "covered")
    protected String covered;
    @XmlAttribute(name = "roomtype")
    protected String roomtype;
    @XmlAttribute(name = "hascontrolpanel")
    protected String hascontrolpanel;
    @XmlAttribute(name = "race")
    protected String race;
    @XmlAttribute(name = "npctemplate")
    protected String npctemplate;
    @XmlAttribute(name = "entitytype")
    protected String entitytype;
    @XmlAttribute(name = "entityrole")
    protected String entityrole;
    @XmlAttribute(name = "controlpost")
    protected String controlpost;
    @XmlAttribute(name = "controlentity")
    protected String controlentity;
    @XmlAttribute(name = "missionactor")
    protected String missionactor;
    @XmlAttribute(name = "representative")
    protected String representative;
    @XmlAttribute(name = "temporaryentity")
    protected String temporaryentity;
    @XmlAttribute(name = "hasmasstraffic")
    protected Boolean hasmasstraffic;
    @XmlAttribute(name = "canclaimownership")
    protected String canclaimownership;
    @XmlAttribute(name = "tradestation")
    protected String tradestation;
    @XmlAttribute(name = "shipyard")
    protected String shipyard;
    @XmlAttribute(name = "wharf")
    protected String wharf;
    @XmlAttribute(name = "equipmentdock")
    protected String equipmentdock;
    @XmlAttribute(name = "defencestation")
    protected String defencestation;
    @XmlAttribute(name = "factionheadquarters")
    protected String factionheadquarters;
    @XmlAttribute(name = "planneddefencestation")
    protected String planneddefencestation;
    @XmlAttribute(name = "plannedequipmentdock")
    protected String plannedequipmentdock;
    @XmlAttribute(name = "plannedfactionheadquarters")
    protected String plannedfactionheadquarters;
    @XmlAttribute(name = "plannedheadquarters")
    protected String plannedheadquarters;
    @XmlAttribute(name = "plannedpiratebase")
    protected String plannedpiratebase;
    @XmlAttribute(name = "plannedshipyard")
    protected String plannedshipyard;
    @XmlAttribute(name = "plannedtradestation")
    protected String plannedtradestation;
    @XmlAttribute(name = "plannedwharf")
    protected String plannedwharf;
    @XmlAttribute(name = "headquarters")
    protected String headquarters;
    @XmlAttribute(name = "piratebase")
    protected String piratebase;

    /**
     * Gets the value of the negate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegate() {
        return negate;
    }

    /**
     * Sets the value of the negate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegate(Boolean value) {
        this.negate = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<String>();
        }
        return this.clazz;
    }

    /**
     * Gets the value of the exactclass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exactclass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExactclass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExactclass() {
        if (exactclass == null) {
            exactclass = new ArrayList<String>();
        }
        return this.exactclass;
    }

    /**
     * Gets the value of the restorable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestorable() {
        return restorable;
    }

    /**
     * Sets the value of the restorable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestorable(String value) {
        this.restorable = value;
    }

    /**
     * Gets the value of the repairable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairable() {
        return repairable;
    }

    /**
     * Sets the value of the repairable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairable(String value) {
        this.repairable = value;
    }

    /**
     * Gets the value of the needsrepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeedsrepair() {
        return needsrepair;
    }

    /**
     * Sets the value of the needsrepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeedsrepair(String value) {
        this.needsrepair = value;
    }

    /**
     * Gets the value of the normalzone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalzone() {
        return normalzone;
    }

    /**
     * Sets the value of the normalzone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalzone(String value) {
        this.normalzone = value;
    }

    /**
     * Gets the value of the tempzone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTempzone() {
        return tempzone;
    }

    /**
     * Sets the value of the tempzone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTempzone(String value) {
        this.tempzone = value;
    }

    /**
     * Gets the value of the accessgrantedto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessgrantedto() {
        return accessgrantedto;
    }

    /**
     * Sets the value of the accessgrantedto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessgrantedto(String value) {
        this.accessgrantedto = value;
    }

    /**
     * Gets the value of the accessrestrictedto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessrestrictedto() {
        return accessrestrictedto;
    }

    /**
     * Sets the value of the accessrestrictedto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessrestrictedto(String value) {
        this.accessrestrictedto = value;
    }

    /**
     * Gets the value of the normalcluster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalcluster() {
        return normalcluster;
    }

    /**
     * Sets the value of the normalcluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalcluster(String value) {
        this.normalcluster = value;
    }

    /**
     * Gets the value of the docked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocked() {
        return docked;
    }

    /**
     * Sets the value of the docked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocked(String value) {
        this.docked = value;
    }

    /**
     * Gets the value of the shiptype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiptype() {
        return shiptype;
    }

    /**
     * Sets the value of the shiptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiptype(String value) {
        this.shiptype = value;
    }

    /**
     * Gets the value of the hasjob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasjob() {
        return hasjob;
    }

    /**
     * Sets the value of the hasjob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasjob(String value) {
        this.hasjob = value;
    }

    /**
     * Gets the value of the job property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJob() {
        return job;
    }

    /**
     * Sets the value of the job property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJob(String value) {
        this.job = value;
    }

    /**
     * Gets the value of the validjobship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidjobship() {
        return validjobship;
    }

    /**
     * Sets the value of the validjobship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidjobship(String value) {
        this.validjobship = value;
    }

    /**
     * Gets the value of the jobtags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobtags() {
        return jobtags;
    }

    /**
     * Sets the value of the jobtags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobtags(String value) {
        this.jobtags = value;
    }

    /**
     * Gets the value of the encounterid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncounterid() {
        return encounterid;
    }

    /**
     * Sets the value of the encounterid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncounterid(String value) {
        this.encounterid = value;
    }

    /**
     * Gets the value of the encountership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncountership() {
        return encountership;
    }

    /**
     * Sets the value of the encountership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncountership(String value) {
        this.encountership = value;
    }

    /**
     * Gets the value of the contested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContested() {
        return contested;
    }

    /**
     * Sets the value of the contested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContested(String value) {
        this.contested = value;
    }

    /**
     * Gets the value of the contestedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContestedby() {
        return contestedby;
    }

    /**
     * Sets the value of the contestedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContestedby(String value) {
        this.contestedby = value;
    }

    /**
     * Gets the value of the macro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacro() {
        return macro;
    }

    /**
     * Sets the value of the macro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacro(String value) {
        this.macro = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the trueowner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrueowner() {
        return trueowner;
    }

    /**
     * Sets the value of the trueowner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrueowner(String value) {
        this.trueowner = value;
    }

    /**
     * Gets the value of the coverowner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverowner() {
        return coverowner;
    }

    /**
     * Sets the value of the coverowner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverowner(String value) {
        this.coverowner = value;
    }

    /**
     * Gets the value of the policefaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicefaction() {
        return policefaction;
    }

    /**
     * Sets the value of the policefaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicefaction(String value) {
        this.policefaction = value;
    }

    /**
     * Gets the value of the negateownerfilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegateownerfilter() {
        return negateownerfilter;
    }

    /**
     * Sets the value of the negateownerfilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegateownerfilter(String value) {
        this.negateownerfilter = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the excluded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcluded() {
        return excluded;
    }

    /**
     * Sets the value of the excluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcluded(String value) {
        this.excluded = value;
    }

    /**
     * Gets the value of the grouptag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrouptag() {
        return grouptag;
    }

    /**
     * Sets the value of the grouptag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrouptag(String value) {
        this.grouptag = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the integrated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrated() {
        return integrated;
    }

    /**
     * Sets the value of the integrated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrated(String value) {
        this.integrated = value;
    }

    /**
     * Gets the value of the invulnerable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvulnerable() {
        return invulnerable;
    }

    /**
     * Sets the value of the invulnerable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvulnerable(String value) {
        this.invulnerable = value;
    }

    /**
     * Gets the value of the hullinvulnerable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullinvulnerable() {
        return hullinvulnerable;
    }

    /**
     * Sets the value of the hullinvulnerable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullinvulnerable(String value) {
        this.hullinvulnerable = value;
    }

    /**
     * Gets the value of the shieldinvulnerable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShieldinvulnerable() {
        return shieldinvulnerable;
    }

    /**
     * Sets the value of the shieldinvulnerable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShieldinvulnerable(String value) {
        this.shieldinvulnerable = value;
    }

    /**
     * Gets the value of the indestructible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndestructible() {
        return indestructible;
    }

    /**
     * Sets the value of the indestructible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndestructible(String value) {
        this.indestructible = value;
    }

    /**
     * Gets the value of the checkoperational property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckoperational() {
        return checkoperational;
    }

    /**
     * Sets the value of the checkoperational property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckoperational(String value) {
        this.checkoperational = value;
    }

    /**
     * Gets the value of the functional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctional() {
        return functional;
    }

    /**
     * Sets the value of the functional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctional(String value) {
        this.functional = value;
    }

    /**
     * Gets the value of the surfaceelement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurfaceelement() {
        return surfaceelement;
    }

    /**
     * Sets the value of the surfaceelement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurfaceelement(String value) {
        this.surfaceelement = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

    /**
     * Gets the value of the known property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKnown() {
        return known;
    }

    /**
     * Sets the value of the known property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKnown(String value) {
        this.known = value;
    }

    /**
     * Gets the value of the knownto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKnownto() {
        return knownto;
    }

    /**
     * Sets the value of the knownto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKnownto(String value) {
        this.knownto = value;
    }

    /**
     * Gets the value of the suspicious property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuspicious() {
        return suspicious;
    }

    /**
     * Sets the value of the suspicious property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuspicious(String value) {
        this.suspicious = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the hastradeoffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHastradeoffer() {
        return hastradeoffer;
    }

    /**
     * Sets the value of the hastradeoffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHastradeoffer(String value) {
        this.hastradeoffer = value;
    }

    /**
     * Gets the value of the tradesknownto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradesknownto() {
        return tradesknownto;
    }

    /**
     * Sets the value of the tradesknownto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradesknownto(String value) {
        this.tradesknownto = value;
    }

    /**
     * Gets the value of the canhaveofferlocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanhaveofferlocation() {
        return canhaveofferlocation;
    }

    /**
     * Sets the value of the canhaveofferlocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanhaveofferlocation(String value) {
        this.canhaveofferlocation = value;
    }

    /**
     * Gets the value of the freemissionofferslot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreemissionofferslot() {
        return freemissionofferslot;
    }

    /**
     * Sets the value of the freemissionofferslot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreemissionofferslot(String value) {
        this.freemissionofferslot = value;
    }

    /**
     * Gets the value of the freesignalleakslot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreesignalleakslot() {
        return freesignalleakslot;
    }

    /**
     * Sets the value of the freesignalleakslot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreesignalleakslot(String value) {
        this.freesignalleakslot = value;
    }

    /**
     * Gets the value of the numfreeactorslots property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumfreeactorslots() {
        return numfreeactorslots;
    }

    /**
     * Sets the value of the numfreeactorslots property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumfreeactorslots(String value) {
        this.numfreeactorslots = value;
    }

    /**
     * Gets the value of the freemissionactorslot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreemissionactorslot() {
        return freemissionactorslot;
    }

    /**
     * Sets the value of the freemissionactorslot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreemissionactorslot(String value) {
        this.freemissionactorslot = value;
    }

    /**
     * Gets the value of the masstraffic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasstraffic() {
        return masstraffic;
    }

    /**
     * Sets the value of the masstraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasstraffic(String value) {
        this.masstraffic = value;
    }

    /**
     * Gets the value of the onlineobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineobject() {
        return onlineobject;
    }

    /**
     * Sets the value of the onlineobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineobject(String value) {
        this.onlineobject = value;
    }

    /**
     * Gets the value of the visitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisitor() {
        return visitor;
    }

    /**
     * Sets the value of the visitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisitor(String value) {
        this.visitor = value;
    }

    /**
     * Gets the value of the walkable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWalkable() {
        return walkable;
    }

    /**
     * Sets the value of the walkable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWalkable(String value) {
        this.walkable = value;
    }

    /**
     * Gets the value of the roompopulationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoompopulationtype() {
        return roompopulationtype;
    }

    /**
     * Sets the value of the roompopulationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoompopulationtype(String value) {
        this.roompopulationtype = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the busy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusy() {
        return busy;
    }

    /**
     * Sets the value of the busy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusy(String value) {
        this.busy = value;
    }

    /**
     * Gets the value of the hasbuildingtask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasbuildingtask() {
        return hasbuildingtask;
    }

    /**
     * Sets the value of the hasbuildingtask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasbuildingtask(String value) {
        this.hasbuildingtask = value;
    }

    /**
     * Gets the value of the canbebuiltby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbebuiltby() {
        return canbebuiltby;
    }

    /**
     * Sets the value of the canbebuiltby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbebuiltby(String value) {
        this.canbebuiltby = value;
    }

    /**
     * Gets the value of the canbebuiltbyany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbebuiltbyany() {
        return canbebuiltbyany;
    }

    /**
     * Sets the value of the canbebuiltbyany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbebuiltbyany(String value) {
        this.canbebuiltbyany = value;
    }

    /**
     * Gets the value of the canbuildfor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbuildfor() {
        return canbuildfor;
    }

    /**
     * Sets the value of the canbuildfor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbuildfor(String value) {
        this.canbuildfor = value;
    }

    /**
     * Gets the value of the canbuildclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbuildclass() {
        return canbuildclass;
    }

    /**
     * Sets the value of the canbuildclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbuildclass(String value) {
        this.canbuildclass = value;
    }

    /**
     * Gets the value of the canbuildships property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbuildships() {
        return canbuildships;
    }

    /**
     * Sets the value of the canbuildships property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbuildships(String value) {
        this.canbuildships = value;
    }

    /**
     * Gets the value of the canequipclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanequipclass() {
        return canequipclass;
    }

    /**
     * Sets the value of the canequipclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanequipclass(String value) {
        this.canequipclass = value;
    }

    /**
     * Gets the value of the cansupplyclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCansupplyclass() {
        return cansupplyclass;
    }

    /**
     * Sets the value of the cansupplyclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCansupplyclass(String value) {
        this.cansupplyclass = value;
    }

    /**
     * Gets the value of the canequipships property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanequipships() {
        return canequipships;
    }

    /**
     * Sets the value of the canequipships property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanequipships(String value) {
        this.canequipships = value;
    }

    /**
     * Gets the value of the cansupplyships property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCansupplyships() {
        return cansupplyships;
    }

    /**
     * Sets the value of the cansupplyships property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCansupplyships(String value) {
        this.cansupplyships = value;
    }

    /**
     * Gets the value of the canbuildequipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbuildequipment() {
        return canbuildequipment;
    }

    /**
     * Sets the value of the canbuildequipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbuildequipment(String value) {
        this.canbuildequipment = value;
    }

    /**
     * Gets the value of the canbuildmacro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbuildmacro() {
        return canbuildmacro;
    }

    /**
     * Sets the value of the canbuildmacro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbuildmacro(String value) {
        this.canbuildmacro = value;
    }

    /**
     * Gets the value of the waretransport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaretransport() {
        return waretransport;
    }

    /**
     * Sets the value of the waretransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaretransport(String value) {
        this.waretransport = value;
    }

    /**
     * Gets the value of the weaponmode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeaponmode() {
        return weaponmode;
    }

    /**
     * Sets the value of the weaponmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeaponmode(String value) {
        this.weaponmode = value;
    }

    /**
     * Gets the value of the weapontype property.
     * 
     * @return
     *     possible object is
     *     {@link Weapontypelookup }
     *     
     */
    public Weapontypelookup getWeapontype() {
        return weapontype;
    }

    /**
     * Sets the value of the weapontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weapontypelookup }
     *     
     */
    public void setWeapontype(Weapontypelookup value) {
        this.weapontype = value;
    }

    /**
     * Gets the value of the primarypurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarypurpose() {
        return primarypurpose;
    }

    /**
     * Sets the value of the primarypurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarypurpose(String value) {
        this.primarypurpose = value;
    }

    /**
     * Gets the value of the deployable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployable() {
        return deployable;
    }

    /**
     * Sets the value of the deployable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployable(String value) {
        this.deployable = value;
    }

    /**
     * Gets the value of the datavault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatavault() {
        return datavault;
    }

    /**
     * Sets the value of the datavault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatavault(String value) {
        this.datavault = value;
    }

    /**
     * Gets the value of the deployablecategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployablecategory() {
        return deployablecategory;
    }

    /**
     * Sets the value of the deployablecategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployablecategory(String value) {
        this.deployablecategory = value;
    }

    /**
     * Gets the value of the mayattack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMayattack() {
        return mayattack;
    }

    /**
     * Sets the value of the mayattack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMayattack(String value) {
        this.mayattack = value;
    }

    /**
     * Gets the value of the maybeattackedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaybeattackedby() {
        return maybeattackedby;
    }

    /**
     * Sets the value of the maybeattackedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaybeattackedby(String value) {
        this.maybeattackedby = value;
    }

    /**
     * Gets the value of the ishostileto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIshostileto() {
        return ishostileto;
    }

    /**
     * Sets the value of the ishostileto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIshostileto(String value) {
        this.ishostileto = value;
    }

    /**
     * Gets the value of the canbepickedup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanbepickedup() {
        return canbepickedup;
    }

    /**
     * Sets the value of the canbepickedup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanbepickedup(String value) {
        this.canbepickedup = value;
    }

    /**
     * Gets the value of the commandeerable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandeerable() {
        return commandeerable;
    }

    /**
     * Sets the value of the commandeerable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandeerable(String value) {
        this.commandeerable = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the hascommander property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHascommander() {
        return hascommander;
    }

    /**
     * Sets the value of the hascommander property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHascommander(String value) {
        this.hascommander = value;
    }

    /**
     * Gets the value of the hascontrolentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHascontrolentity() {
        return hascontrolentity;
    }

    /**
     * Sets the value of the hascontrolentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHascontrolentity(String value) {
        this.hascontrolentity = value;
    }

    /**
     * Gets the value of the capturable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturable() {
        return capturable;
    }

    /**
     * Sets the value of the capturable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturable(String value) {
        this.capturable = value;
    }

    /**
     * Gets the value of the accelerator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccelerator() {
        return accelerator;
    }

    /**
     * Sets the value of the accelerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccelerator(String value) {
        this.accelerator = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActive(String value) {
        this.active = value;
    }

    /**
     * Gets the value of the paused property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaused() {
        return paused;
    }

    /**
     * Sets the value of the paused property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaused(String value) {
        this.paused = value;
    }

    /**
     * Gets the value of the pausedmanually property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPausedmanually() {
        return pausedmanually;
    }

    /**
     * Sets the value of the pausedmanually property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPausedmanually(String value) {
        this.pausedmanually = value;
    }

    /**
     * Gets the value of the signalleaktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalleaktype() {
        return signalleaktype;
    }

    /**
     * Sets the value of the signalleaktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalleaktype(String value) {
        this.signalleaktype = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the personalextension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalextension() {
        return personalextension;
    }

    /**
     * Sets the value of the personalextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalextension(String value) {
        this.personalextension = value;
    }

    /**
     * Gets the value of the covered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCovered() {
        return covered;
    }

    /**
     * Sets the value of the covered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCovered(String value) {
        this.covered = value;
    }

    /**
     * Gets the value of the roomtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * Sets the value of the roomtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomtype(String value) {
        this.roomtype = value;
    }

    /**
     * Gets the value of the hascontrolpanel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHascontrolpanel() {
        return hascontrolpanel;
    }

    /**
     * Sets the value of the hascontrolpanel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHascontrolpanel(String value) {
        this.hascontrolpanel = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRace(String value) {
        this.race = value;
    }

    /**
     * Gets the value of the npctemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpctemplate() {
        return npctemplate;
    }

    /**
     * Sets the value of the npctemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpctemplate(String value) {
        this.npctemplate = value;
    }

    /**
     * Gets the value of the entitytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitytype() {
        return entitytype;
    }

    /**
     * Sets the value of the entitytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitytype(String value) {
        this.entitytype = value;
    }

    /**
     * Gets the value of the entityrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityrole() {
        return entityrole;
    }

    /**
     * Sets the value of the entityrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityrole(String value) {
        this.entityrole = value;
    }

    /**
     * Gets the value of the controlpost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlpost() {
        return controlpost;
    }

    /**
     * Sets the value of the controlpost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlpost(String value) {
        this.controlpost = value;
    }

    /**
     * Gets the value of the controlentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlentity() {
        return controlentity;
    }

    /**
     * Sets the value of the controlentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlentity(String value) {
        this.controlentity = value;
    }

    /**
     * Gets the value of the missionactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissionactor() {
        return missionactor;
    }

    /**
     * Sets the value of the missionactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissionactor(String value) {
        this.missionactor = value;
    }

    /**
     * Gets the value of the representative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * Sets the value of the representative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentative(String value) {
        this.representative = value;
    }

    /**
     * Gets the value of the temporaryentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporaryentity() {
        return temporaryentity;
    }

    /**
     * Sets the value of the temporaryentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporaryentity(String value) {
        this.temporaryentity = value;
    }

    /**
     * Gets the value of the hasmasstraffic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasmasstraffic() {
        return hasmasstraffic;
    }

    /**
     * Sets the value of the hasmasstraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasmasstraffic(Boolean value) {
        this.hasmasstraffic = value;
    }

    /**
     * Gets the value of the canclaimownership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanclaimownership() {
        return canclaimownership;
    }

    /**
     * Sets the value of the canclaimownership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanclaimownership(String value) {
        this.canclaimownership = value;
    }

    /**
     * Gets the value of the tradestation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradestation() {
        return tradestation;
    }

    /**
     * Sets the value of the tradestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradestation(String value) {
        this.tradestation = value;
    }

    /**
     * Gets the value of the shipyard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipyard() {
        return shipyard;
    }

    /**
     * Sets the value of the shipyard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipyard(String value) {
        this.shipyard = value;
    }

    /**
     * Gets the value of the wharf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWharf() {
        return wharf;
    }

    /**
     * Sets the value of the wharf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWharf(String value) {
        this.wharf = value;
    }

    /**
     * Gets the value of the equipmentdock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentdock() {
        return equipmentdock;
    }

    /**
     * Sets the value of the equipmentdock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentdock(String value) {
        this.equipmentdock = value;
    }

    /**
     * Gets the value of the defencestation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefencestation() {
        return defencestation;
    }

    /**
     * Sets the value of the defencestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefencestation(String value) {
        this.defencestation = value;
    }

    /**
     * Gets the value of the factionheadquarters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactionheadquarters() {
        return factionheadquarters;
    }

    /**
     * Sets the value of the factionheadquarters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactionheadquarters(String value) {
        this.factionheadquarters = value;
    }

    /**
     * Gets the value of the planneddefencestation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanneddefencestation() {
        return planneddefencestation;
    }

    /**
     * Sets the value of the planneddefencestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanneddefencestation(String value) {
        this.planneddefencestation = value;
    }

    /**
     * Gets the value of the plannedequipmentdock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedequipmentdock() {
        return plannedequipmentdock;
    }

    /**
     * Sets the value of the plannedequipmentdock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedequipmentdock(String value) {
        this.plannedequipmentdock = value;
    }

    /**
     * Gets the value of the plannedfactionheadquarters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedfactionheadquarters() {
        return plannedfactionheadquarters;
    }

    /**
     * Sets the value of the plannedfactionheadquarters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedfactionheadquarters(String value) {
        this.plannedfactionheadquarters = value;
    }

    /**
     * Gets the value of the plannedheadquarters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedheadquarters() {
        return plannedheadquarters;
    }

    /**
     * Sets the value of the plannedheadquarters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedheadquarters(String value) {
        this.plannedheadquarters = value;
    }

    /**
     * Gets the value of the plannedpiratebase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedpiratebase() {
        return plannedpiratebase;
    }

    /**
     * Sets the value of the plannedpiratebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedpiratebase(String value) {
        this.plannedpiratebase = value;
    }

    /**
     * Gets the value of the plannedshipyard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedshipyard() {
        return plannedshipyard;
    }

    /**
     * Sets the value of the plannedshipyard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedshipyard(String value) {
        this.plannedshipyard = value;
    }

    /**
     * Gets the value of the plannedtradestation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedtradestation() {
        return plannedtradestation;
    }

    /**
     * Sets the value of the plannedtradestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedtradestation(String value) {
        this.plannedtradestation = value;
    }

    /**
     * Gets the value of the plannedwharf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedwharf() {
        return plannedwharf;
    }

    /**
     * Sets the value of the plannedwharf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedwharf(String value) {
        this.plannedwharf = value;
    }

    /**
     * Gets the value of the headquarters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadquarters() {
        return headquarters;
    }

    /**
     * Sets the value of the headquarters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadquarters(String value) {
        this.headquarters = value;
    }

    /**
     * Gets the value of the piratebase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiratebase() {
        return piratebase;
    }

    /**
     * Sets the value of the piratebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiratebase(String value) {
        this.piratebase = value;
    }

}
