//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchwaresorcargo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchwaresorcargo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="ware"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="ware" use="required" type="{}expression" /&gt;
 *                 &lt;attribute name="exact" type="{}expression" /&gt;
 *                 &lt;attribute name="min" type="{}expression" /&gt;
 *                 &lt;attribute name="max" type="{}expression" /&gt;
 *                 &lt;attribute name="negate" type="{}negatefilter" /&gt;
 *                 &lt;attribute name="comment" type="{}comment" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchwaresorcargo", propOrder = {
    "ware"
})
public class Matchwaresorcargo {

    protected List<Matchwaresorcargo.Ware> ware;

    /**
     * Gets the value of the ware property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ware property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Matchwaresorcargo.Ware }
     * 
     * 
     */
    public List<Matchwaresorcargo.Ware> getWare() {
        if (ware == null) {
            ware = new ArrayList<Matchwaresorcargo.Ware>();
        }
        return this.ware;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="ware" use="required" type="{}expression" /&gt;
     *       &lt;attribute name="exact" type="{}expression" /&gt;
     *       &lt;attribute name="min" type="{}expression" /&gt;
     *       &lt;attribute name="max" type="{}expression" /&gt;
     *       &lt;attribute name="negate" type="{}negatefilter" /&gt;
     *       &lt;attribute name="comment" type="{}comment" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ware {

        @XmlAttribute(name = "ware", required = true)
        protected String ware;
        @XmlAttribute(name = "exact")
        protected String exact;
        @XmlAttribute(name = "min")
        protected String min;
        @XmlAttribute(name = "max")
        protected String max;
        @XmlAttribute(name = "negate")
        protected Boolean negate;
        @XmlAttribute(name = "comment")
        protected String comment;

        /**
         * Gets the value of the ware property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWare() {
            return ware;
        }

        /**
         * Sets the value of the ware property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWare(String value) {
            this.ware = value;
        }

        /**
         * Gets the value of the exact property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExact() {
            return exact;
        }

        /**
         * Sets the value of the exact property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExact(String value) {
            this.exact = value;
        }

        /**
         * Gets the value of the min property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMin(String value) {
            this.min = value;
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMax(String value) {
            this.max = value;
        }

        /**
         * Gets the value of the negate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNegate() {
            return negate;
        }

        /**
         * Sets the value of the negate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNegate(Boolean value) {
            this.negate = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComment(String value) {
            this.comment = value;
        }

    }

}
