//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="module" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="category" type="{}moduledbcategory" minOccurs="0"/&gt;
 *                   &lt;group ref="{}createmodule"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attGroup ref="{}createmodule"/&gt;
 *                 &lt;attribute name="id" use="required" type="{}idname" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "module"
})
@XmlRootElement(name = "modules")
public class Modules {

    protected List<Modules.Module> module;

    /**
     * Gets the value of the module property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the module property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modules.Module }
     * 
     * 
     */
    public List<Modules.Module> getModule() {
        if (module == null) {
            module = new ArrayList<Modules.Module>();
        }
        return this.module;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="category" type="{}moduledbcategory" minOccurs="0"/&gt;
     *         &lt;group ref="{}createmodule"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attGroup ref="{}createmodule"/&gt;
     *       &lt;attribute name="id" use="required" type="{}idname" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "compatibilities",
        "select"
    })
    public static class Module {

        protected Moduledbcategory category;
        protected be.celludriel.universegenerator.model.xml.libraries.God.Products.Product.Module.Compatibilities compatibilities;
        protected Moduledbcategoryselect select;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "macro")
        protected String macro;
        @XmlAttribute(name = "group")
        protected String group;
        @XmlAttribute(name = "ref")
        protected String ref;
        @XmlAttribute(name = "base")
        protected String base;

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link Moduledbcategory }
         *     
         */
        public Moduledbcategory getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link Moduledbcategory }
         *     
         */
        public void setCategory(Moduledbcategory value) {
            this.category = value;
        }

        /**
         * Gets the value of the compatibilities property.
         * 
         * @return
         *     possible object is
         *     {@link be.celludriel.universegenerator.model.xml.libraries.God.Products.Product.Module.Compatibilities }
         *     
         */
        public be.celludriel.universegenerator.model.xml.libraries.God.Products.Product.Module.Compatibilities getCompatibilities() {
            return compatibilities;
        }

        /**
         * Sets the value of the compatibilities property.
         * 
         * @param value
         *     allowed object is
         *     {@link be.celludriel.universegenerator.model.xml.libraries.God.Products.Product.Module.Compatibilities }
         *     
         */
        public void setCompatibilities(be.celludriel.universegenerator.model.xml.libraries.God.Products.Product.Module.Compatibilities value) {
            this.compatibilities = value;
        }

        /**
         * Gets the value of the select property.
         * 
         * @return
         *     possible object is
         *     {@link Moduledbcategoryselect }
         *     
         */
        public Moduledbcategoryselect getSelect() {
            return select;
        }

        /**
         * Sets the value of the select property.
         * 
         * @param value
         *     allowed object is
         *     {@link Moduledbcategoryselect }
         *     
         */
        public void setSelect(Moduledbcategoryselect value) {
            this.select = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the macro property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMacro() {
            return macro;
        }

        /**
         * Sets the value of the macro property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMacro(String value) {
            this.macro = value;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroup(String value) {
            this.group = value;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }

        /**
         * Gets the value of the base property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBase() {
            return base;
        }

        /**
         * Sets the value of the base property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBase(String value) {
            this.base = value;
        }

    }

}
