//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.celludriel.universegenerator.model.xml.libraries package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MatchtradeoffervaluesAmount_QNAME = new QName("", "amount");
    private final static QName _MatchtradeoffervaluesMinamount_QNAME = new QName("", "minamount");
    private final static QName _MatchtradeoffervaluesTotalprice_QNAME = new QName("", "totalprice");
    private final static QName _MatchtradeoffervaluesMinprice_QNAME = new QName("", "minprice");
    private final static QName _MatchbaseMatch_QNAME = new QName("", "match");
    private final static QName _MatchbaseMatchAny_QNAME = new QName("", "match_any");
    private final static QName _MatchbaseMatchParent_QNAME = new QName("", "match_parent");
    private final static QName _MatchbaseMatchContext_QNAME = new QName("", "match_context");
    private final static QName _MatchbaseMatchChild_QNAME = new QName("", "match_child");
    private final static QName _MatchbaseMatchContent_QNAME = new QName("", "match_content");
    private final static QName _MatchbaseMatchMacroChildren_QNAME = new QName("", "match_macro_children");
    private final static QName _MatchbaseMatchHull_QNAME = new QName("", "match_hull");
    private final static QName _MatchbaseMatchMaxHull_QNAME = new QName("", "match_max_hull");
    private final static QName _MatchbaseMatchShield_QNAME = new QName("", "match_shield");
    private final static QName _MatchbaseMatchSecrecyLevel_QNAME = new QName("", "match_secrecy_level");
    private final static QName _MatchbaseMatchAttention_QNAME = new QName("", "match_attention");
    private final static QName _MatchbaseMatchRevealedPercentage_QNAME = new QName("", "match_revealed_percentage");
    private final static QName _MatchbaseMatchPilot_QNAME = new QName("", "match_pilot");
    private final static QName _MatchbaseMatchDistance_QNAME = new QName("", "match_distance");
    private final static QName _MatchbaseMatchGateDistance_QNAME = new QName("", "match_gate_distance");
    private final static QName _MatchbaseMatchUseBlacklist_QNAME = new QName("", "match_use_blacklist");
    private final static QName _MatchbaseMatchSize_QNAME = new QName("", "match_size");
    private final static QName _MatchbaseMatchIsInViewOf_QNAME = new QName("", "match_is_in_view_of");
    private final static QName _MatchbaseMatchBuyoffer_QNAME = new QName("", "match_buyoffer");
    private final static QName _MatchbaseMatchSelloffer_QNAME = new QName("", "match_selloffer");
    private final static QName _MatchbaseMatchBuild_QNAME = new QName("", "match_build");
    private final static QName _MatchbaseMatchProducts_QNAME = new QName("", "match_products");
    private final static QName _MatchbaseMatchResources_QNAME = new QName("", "match_resources");
    private final static QName _MatchbaseMatchAnyCargo_QNAME = new QName("", "match_any_cargo");
    private final static QName _MatchbaseMatchAnyWares_QNAME = new QName("", "match_any_wares");
    private final static QName _MatchbaseMatchBasketWares_QNAME = new QName("", "match_basket_wares");
    private final static QName _MatchbaseMatchRelationOf_QNAME = new QName("", "match_relation_of");
    private final static QName _MatchbaseMatchRelationTo_QNAME = new QName("", "match_relation_to");
    private final static QName _MatchbaseMatchRequiresLicence_QNAME = new QName("", "match_requires_licence");
    private final static QName _MatchbaseMatchDock_QNAME = new QName("", "match_dock");
    private final static QName _MatchbaseMatchUnitsStored_QNAME = new QName("", "match_units_stored");
    private final static QName _MatchbaseMatchUnitsAvailable_QNAME = new QName("", "match_units_available");
    private final static QName _MatchbaseMatchUnitsUnavailable_QNAME = new QName("", "match_units_unavailable");
    private final static QName _MatchbaseMatchCargo_QNAME = new QName("", "match_cargo");
    private final static QName _MatchbaseMatchWares_QNAME = new QName("", "match_wares");
    private final static QName _MatchbaseMatchLoadout_QNAME = new QName("", "match_loadout");
    private final static QName _MatchbaseMatchWeaponMod_QNAME = new QName("", "match_weapon_mod");
    private final static QName _MatchbaseMatchEngineMod_QNAME = new QName("", "match_engine_mod");
    private final static QName _MatchbaseMatchShieldMod_QNAME = new QName("", "match_shield_mod");
    private final static QName _MatchbaseMatchShipMod_QNAME = new QName("", "match_ship_mod");
    private final static QName _MatchbaseMatchPaintMod_QNAME = new QName("", "match_paint_mod");
    private final static QName _MatchbaseMatchAnyEquipmentMod_QNAME = new QName("", "match_any_equipment_mod");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.celludriel.universegenerator.model.xml.libraries
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ships }
     * 
     */
    public Ships createShips() {
        return new Ships();
    }

    /**
     * Create an instance of {@link Characters }
     * 
     */
    public Characters createCharacters() {
        return new Characters();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Modules }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Modules createModules() {
        return new be.celludriel.universegenerator.model.xml.libraries.Modules();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link Props }
     * 
     */
    public Props createProps() {
        return new Props();
    }

    /**
     * Create an instance of {@link Modulesets }
     * 
     */
    public Modulesets createModulesets() {
        return new Modulesets();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Stations }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Stations createStations() {
        return new be.celludriel.universegenerator.model.xml.libraries.Stations();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link God }
     * 
     */
    public God createGod() {
        return new God();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults createDefaults() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults();
    }

    /**
     * Create an instance of {@link Worldshaderparams }
     * 
     */
    public Worldshaderparams createWorldshaderparams() {
        return new Worldshaderparams();
    }

    /**
     * Create an instance of {@link Worldshaderparams.Shaderparam }
     * 
     */
    public Worldshaderparams.Shaderparam createWorldshaderparamsShaderparam() {
        return new Worldshaderparams.Shaderparam();
    }

    /**
     * Create an instance of {@link Godlocationfilters }
     * 
     */
    public Godlocationfilters createGodlocationfilters() {
        return new Godlocationfilters();
    }

    /**
     * Create an instance of {@link Positionrange }
     * 
     */
    public Positionrange createPositionrange() {
        return new Positionrange();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Joborder }
     * 
     */
    public Joborder createJoborder() {
        return new Joborder();
    }

    /**
     * Create an instance of {@link Terraformingpredecessors }
     * 
     */
    public Terraformingpredecessors createTerraformingpredecessors() {
        return new Terraformingpredecessors();
    }

    /**
     * Create an instance of {@link Terraformingremovedprojects }
     * 
     */
    public Terraformingremovedprojects createTerraformingremovedprojects() {
        return new Terraformingremovedprojects();
    }

    /**
     * Create an instance of {@link Propdbcategory }
     * 
     */
    public Propdbcategory createPropdbcategory() {
        return new Propdbcategory();
    }

    /**
     * Create an instance of {@link Selectrandom }
     * 
     */
    public Selectrandom createSelectrandom() {
        return new Selectrandom();
    }

    /**
     * Create an instance of {@link Matchtrade }
     * 
     */
    public Matchtrade createMatchtrade() {
        return new Matchtrade();
    }

    /**
     * Create an instance of {@link Matchwaresorcargo }
     * 
     */
    public Matchwaresorcargo createMatchwaresorcargo() {
        return new Matchwaresorcargo();
    }

    /**
     * Create an instance of {@link Matchbase }
     * 
     */
    public Matchbase createMatchbase() {
        return new Matchbase();
    }

    /**
     * Create an instance of {@link Matchbase.MatchGateDistance }
     * 
     */
    public Matchbase.MatchGateDistance createMatchbaseMatchGateDistance() {
        return new Matchbase.MatchGateDistance();
    }

    /**
     * Create an instance of {@link Filedoc }
     * 
     */
    public Filedoc createFiledoc() {
        return new Filedoc();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset createDefaultsDataset() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties createDefaultsDatasetProperties() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds createDefaultsDatasetPropertiesWorlds() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System createDefaultsDatasetPropertiesSystem() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets createDefaultsDatasetPropertiesSystemPlanets() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet createDefaultsDatasetPropertiesSystemPlanetsPlanet() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons createDefaultsDatasetPropertiesSystemPlanetsPlanetMoons() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns createDefaultsDatasetPropertiesSystemSuns() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds createDefaultsDatasetPropertiesSounds() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds();
    }

    /**
     * Create an instance of {@link God.Products }
     * 
     */
    public God.Products createGodProducts() {
        return new God.Products();
    }

    /**
     * Create an instance of {@link God.Products.Product }
     * 
     */
    public God.Products.Product createGodProductsProduct() {
        return new God.Products.Product();
    }

    /**
     * Create an instance of {@link God.Products.Product.Module }
     * 
     */
    public God.Products.Product.Module createGodProductsProductModule() {
        return new God.Products.Product.Module();
    }

    /**
     * Create an instance of {@link God.Products.Product.Module.Compatibilities }
     * 
     */
    public God.Products.Product.Module.Compatibilities createGodProductsProductModuleCompatibilities() {
        return new God.Products.Product.Module.Compatibilities();
    }

    /**
     * Create an instance of {@link God.Stations }
     * 
     */
    public God.Stations createGodStations() {
        return new God.Stations();
    }

    /**
     * Create an instance of {@link God.Stations.Station }
     * 
     */
    public God.Stations.Station createGodStationsStation() {
        return new God.Stations.Station();
    }

    /**
     * Create an instance of {@link God.Stations.Station.StationElement }
     * 
     */
    public God.Stations.Station.StationElement createGodStationsStationStation() {
        return new God.Stations.Station.StationElement();
    }

    /**
     * Create an instance of {@link God.Stations.Station.StationElement.Loadout }
     * 
     */
    public God.Stations.Station.StationElement.Loadout createGodStationsStationStationLoadout() {
        return new God.Stations.Station.StationElement.Loadout();
    }

    /**
     * Create an instance of {@link God.Stations.Defaults }
     * 
     */
    public God.Stations.Defaults createGodStationsDefaults() {
        return new God.Stations.Defaults();
    }

    /**
     * Create an instance of {@link God.Stations.Defaults.Location }
     * 
     */
    public God.Stations.Defaults.Location createGodStationsDefaultsLocation() {
        return new God.Stations.Defaults.Location();
    }

    /**
     * Create an instance of {@link God.Objects }
     * 
     */
    public God.Objects createGodObjects() {
        return new God.Objects();
    }

    /**
     * Create an instance of {@link God.Objects.Object }
     * 
     */
    public God.Objects.Object createGodObjectsObject() {
        return new God.Objects.Object();
    }

    /**
     * Create an instance of {@link God.Objects.Object.ObjectElement }
     * 
     */
    public God.Objects.Object.ObjectElement createGodObjectsObjectObject() {
        return new God.Objects.Object.ObjectElement();
    }

    /**
     * Create an instance of {@link Jobs.Job }
     * 
     */
    public Jobs.Job createJobsJob() {
        return new Jobs.Job();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic }
     * 
     */
    public Jobs.Job.Masstraffic createJobsJobMasstraffic() {
        return new Jobs.Job.Masstraffic();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People }
     * 
     */
    public Jobs.Job.Masstraffic.People createJobsJobMasstrafficPeople() {
        return new Jobs.Job.Masstraffic.People();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person createJobsJobMasstrafficPeoplePerson() {
        return new Jobs.Job.Masstraffic.People.Person();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Skills }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Skills createJobsJobMasstrafficPeoplePersonSkills() {
        return new Jobs.Job.Masstraffic.People.Person.Skills();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Units }
     * 
     */
    public Jobs.Job.Masstraffic.Units createJobsJobMasstrafficUnits() {
        return new Jobs.Job.Masstraffic.Units();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Inventory }
     * 
     */
    public Jobs.Job.Masstraffic.Inventory createJobsJobMasstrafficInventory() {
        return new Jobs.Job.Masstraffic.Inventory();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Inventory.Wares }
     * 
     */
    public Jobs.Job.Masstraffic.Inventory.Wares createJobsJobMasstrafficInventoryWares() {
        return new Jobs.Job.Masstraffic.Inventory.Wares();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Cargo }
     * 
     */
    public Jobs.Job.Masstraffic.Cargo createJobsJobMasstrafficCargo() {
        return new Jobs.Job.Masstraffic.Cargo();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Cargo.Wares }
     * 
     */
    public Jobs.Job.Masstraffic.Cargo.Wares createJobsJobMasstrafficCargoWares() {
        return new Jobs.Job.Masstraffic.Cargo.Wares();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Ammo }
     * 
     */
    public Jobs.Job.Masstraffic.Ammo createJobsJobMasstrafficAmmo() {
        return new Jobs.Job.Masstraffic.Ammo();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Ammo.Macro }
     * 
     */
    public Jobs.Job.Masstraffic.Ammo.Macro createJobsJobMasstrafficAmmoMacro() {
        return new Jobs.Job.Masstraffic.Ammo.Macro();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods createJobsJobMasstrafficEquipmentmods() {
        return new Jobs.Job.Masstraffic.Equipmentmods();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Loadout }
     * 
     */
    public Jobs.Job.Masstraffic.Loadout createJobsJobMasstrafficLoadout() {
        return new Jobs.Job.Masstraffic.Loadout();
    }

    /**
     * Create an instance of {@link Jobs.Job.Subordinates }
     * 
     */
    public Jobs.Job.Subordinates createJobsJobSubordinates() {
        return new Jobs.Job.Subordinates();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location }
     * 
     */
    public Jobs.Job.Location createJobsJobLocation() {
        return new Jobs.Job.Location();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factionlicences }
     * 
     */
    public Jobs.Job.Location.Factionlicences createJobsJobLocationFactionlicences() {
        return new Jobs.Job.Location.Factionlicences();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factionraces }
     * 
     */
    public Jobs.Job.Location.Factionraces createJobsJobLocationFactionraces() {
        return new Jobs.Job.Location.Factionraces();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Policefaction }
     * 
     */
    public Jobs.Job.Location.Policefaction createJobsJobLocationPolicefaction() {
        return new Jobs.Job.Location.Policefaction();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factions }
     * 
     */
    public Jobs.Job.Location.Factions createJobsJobLocationFactions() {
        return new Jobs.Job.Location.Factions();
    }

    /**
     * Create an instance of {@link Modulesets.Set }
     * 
     */
    public Modulesets.Set createModulesetsSet() {
        return new Modulesets.Set();
    }

    /**
     * Create an instance of {@link Ships.Ship }
     * 
     */
    public Ships.Ship createShipsShip() {
        return new Ships.Ship();
    }

    /**
     * Create an instance of {@link Characters.Character }
     * 
     */
    public Characters.Character createCharactersCharacter() {
        return new Characters.Character();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Modules.Module }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Modules.Module createModulesModule() {
        return new be.celludriel.universegenerator.model.xml.libraries.Modules.Module();
    }

    /**
     * Create an instance of {@link Rooms.Room }
     * 
     */
    public Rooms.Room createRoomsRoom() {
        return new Rooms.Room();
    }

    /**
     * Create an instance of {@link Props.Prop }
     * 
     */
    public Props.Prop createPropsProp() {
        return new Props.Prop();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Stations.Station }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Stations.Station createStationsStation() {
        return new be.celludriel.universegenerator.model.xml.libraries.Stations.Station();
    }

    /**
     * Create an instance of {@link Jobs.Gamestart }
     * 
     */
    public Jobs.Gamestart createJobsGamestart() {
        return new Jobs.Gamestart();
    }

    /**
     * Create an instance of {@link God.Gamestart }
     * 
     */
    public God.Gamestart createGodGamestart() {
        return new God.Gamestart();
    }

    /**
     * Create an instance of {@link Matchsubfilter }
     * 
     */
    public Matchsubfilter createMatchsubfilter() {
        return new Matchsubfilter();
    }

    /**
     * Create an instance of {@link Matchsubfilterrange }
     * 
     */
    public Matchsubfilterrange createMatchsubfilterrange() {
        return new Matchsubfilterrange();
    }

    /**
     * Create an instance of {@link Matchtradeoffer }
     * 
     */
    public Matchtradeoffer createMatchtradeoffer() {
        return new Matchtradeoffer();
    }

    /**
     * Create an instance of {@link Matchbuyer }
     * 
     */
    public Matchbuyer createMatchbuyer() {
        return new Matchbuyer();
    }

    /**
     * Create an instance of {@link Matchseller }
     * 
     */
    public Matchseller createMatchseller() {
        return new Matchseller();
    }

    /**
     * Create an instance of {@link Matchwarelist }
     * 
     */
    public Matchwarelist createMatchwarelist() {
        return new Matchwarelist();
    }

    /**
     * Create an instance of {@link Matchrange }
     * 
     */
    public Matchrange createMatchrange() {
        return new Matchrange();
    }

    /**
     * Create an instance of {@link Matchrevealedpercentage }
     * 
     */
    public Matchrevealedpercentage createMatchrevealedpercentage() {
        return new Matchrevealedpercentage();
    }

    /**
     * Create an instance of {@link Matchunits }
     * 
     */
    public Matchunits createMatchunits() {
        return new Matchunits();
    }

    /**
     * Create an instance of {@link Matchtradeoffervalues }
     * 
     */
    public Matchtradeoffervalues createMatchtradeoffervalues() {
        return new Matchtradeoffervalues();
    }

    /**
     * Create an instance of {@link Matchbuild }
     * 
     */
    public Matchbuild createMatchbuild() {
        return new Matchbuild();
    }

    /**
     * Create an instance of {@link Matchloadout }
     * 
     */
    public Matchloadout createMatchloadout() {
        return new Matchloadout();
    }

    /**
     * Create an instance of {@link Matchweaponmod }
     * 
     */
    public Matchweaponmod createMatchweaponmod() {
        return new Matchweaponmod();
    }

    /**
     * Create an instance of {@link Matchenginemod }
     * 
     */
    public Matchenginemod createMatchenginemod() {
        return new Matchenginemod();
    }

    /**
     * Create an instance of {@link Matchshieldmod }
     * 
     */
    public Matchshieldmod createMatchshieldmod() {
        return new Matchshieldmod();
    }

    /**
     * Create an instance of {@link Matchshipmod }
     * 
     */
    public Matchshipmod createMatchshipmod() {
        return new Matchshipmod();
    }

    /**
     * Create an instance of {@link Matchpaintmod }
     * 
     */
    public Matchpaintmod createMatchpaintmod() {
        return new Matchpaintmod();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link Rotation }
     * 
     */
    public Rotation createRotation() {
        return new Rotation();
    }

    /**
     * Create an instance of {@link Boundingbox }
     * 
     */
    public Boundingbox createBoundingbox() {
        return new Boundingbox();
    }

    /**
     * Create an instance of {@link Safepos }
     * 
     */
    public Safepos createSafepos() {
        return new Safepos();
    }

    /**
     * Create an instance of {@link Createobjectsafepos }
     * 
     */
    public Createobjectsafepos createCreateobjectsafepos() {
        return new Createobjectsafepos();
    }

    /**
     * Create an instance of {@link Orientation }
     * 
     */
    public Orientation createOrientation() {
        return new Orientation();
    }

    /**
     * Create an instance of {@link Componentoffset }
     * 
     */
    public Componentoffset createComponentoffset() {
        return new Componentoffset();
    }

    /**
     * Create an instance of {@link Rangefilter }
     * 
     */
    public Rangefilter createRangefilter() {
        return new Rangefilter();
    }

    /**
     * Create an instance of {@link Shipdbcategory }
     * 
     */
    public Shipdbcategory createShipdbcategory() {
        return new Shipdbcategory();
    }

    /**
     * Create an instance of {@link Shipdbcategoryselect }
     * 
     */
    public Shipdbcategoryselect createShipdbcategoryselect() {
        return new Shipdbcategoryselect();
    }

    /**
     * Create an instance of {@link Characterdbcategory }
     * 
     */
    public Characterdbcategory createCharacterdbcategory() {
        return new Characterdbcategory();
    }

    /**
     * Create an instance of {@link Characterdbcategoryselect }
     * 
     */
    public Characterdbcategoryselect createCharacterdbcategoryselect() {
        return new Characterdbcategoryselect();
    }

    /**
     * Create an instance of {@link Moduledbcategory }
     * 
     */
    public Moduledbcategory createModuledbcategory() {
        return new Moduledbcategory();
    }

    /**
     * Create an instance of {@link Moduledbcategoryselect }
     * 
     */
    public Moduledbcategoryselect createModuledbcategoryselect() {
        return new Moduledbcategoryselect();
    }

    /**
     * Create an instance of {@link Roomdbcategory }
     * 
     */
    public Roomdbcategory createRoomdbcategory() {
        return new Roomdbcategory();
    }

    /**
     * Create an instance of {@link Stationdbcategory }
     * 
     */
    public Stationdbcategory createStationdbcategory() {
        return new Stationdbcategory();
    }

    /**
     * Create an instance of {@link Stationdbcategoryselect }
     * 
     */
    public Stationdbcategoryselect createStationdbcategoryselect() {
        return new Stationdbcategoryselect();
    }

    /**
     * Create an instance of {@link EventPlayerpricemodifier }
     * 
     */
    public EventPlayerpricemodifier createEventPlayerpricemodifier() {
        return new EventPlayerpricemodifier();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Loadout }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Loadout createLoadout() {
        return new be.celludriel.universegenerator.model.xml.libraries.Loadout();
    }

    /**
     * Create an instance of {@link Loadoutmacro }
     * 
     */
    public Loadoutmacro createLoadoutmacro() {
        return new Loadoutmacro();
    }

    /**
     * Create an instance of {@link Loadoutgroup }
     * 
     */
    public Loadoutgroup createLoadoutgroup() {
        return new Loadoutgroup();
    }

    /**
     * Create an instance of {@link Loadoutammo }
     * 
     */
    public Loadoutammo createLoadoutammo() {
        return new Loadoutammo();
    }

    /**
     * Create an instance of {@link Loadoutsoftware }
     * 
     */
    public Loadoutsoftware createLoadoutsoftware() {
        return new Loadoutsoftware();
    }

    /**
     * Create an instance of {@link Loadoutvirtualmacro }
     * 
     */
    public Loadoutvirtualmacro createLoadoutvirtualmacro() {
        return new Loadoutvirtualmacro();
    }

    /**
     * Create an instance of {@link Loadoutcrew }
     * 
     */
    public Loadoutcrew createLoadoutcrew() {
        return new Loadoutcrew();
    }

    /**
     * Create an instance of {@link Terraformingcondition }
     * 
     */
    public Terraformingcondition createTerraformingcondition() {
        return new Terraformingcondition();
    }

    /**
     * Create an instance of {@link Terraformingconditions }
     * 
     */
    public Terraformingconditions createTerraformingconditions() {
        return new Terraformingconditions();
    }

    /**
     * Create an instance of {@link Terraformingeffect }
     * 
     */
    public Terraformingeffect createTerraformingeffect() {
        return new Terraformingeffect();
    }

    /**
     * Create an instance of {@link Terraformingeffects }
     * 
     */
    public Terraformingeffects createTerraformingeffects() {
        return new Terraformingeffects();
    }

    /**
     * Create an instance of {@link Terraformingsideeffect }
     * 
     */
    public Terraformingsideeffect createTerraformingsideeffect() {
        return new Terraformingsideeffect();
    }

    /**
     * Create an instance of {@link Terraformingsideeffects }
     * 
     */
    public Terraformingsideeffects createTerraformingsideeffects() {
        return new Terraformingsideeffects();
    }

    /**
     * Create an instance of {@link Terraformingrebate }
     * 
     */
    public Terraformingrebate createTerraformingrebate() {
        return new Terraformingrebate();
    }

    /**
     * Create an instance of {@link Terraformingrebates }
     * 
     */
    public Terraformingrebates createTerraformingrebates() {
        return new Terraformingrebates();
    }

    /**
     * Create an instance of {@link Terraformingwareamount }
     * 
     */
    public Terraformingwareamount createTerraformingwareamount() {
        return new Terraformingwareamount();
    }

    /**
     * Create an instance of {@link Terraformingresources }
     * 
     */
    public Terraformingresources createTerraformingresources() {
        return new Terraformingresources();
    }

    /**
     * Create an instance of {@link Terraformingdelivery }
     * 
     */
    public Terraformingdelivery createTerraformingdelivery() {
        return new Terraformingdelivery();
    }

    /**
     * Create an instance of {@link Terraformingdeliveries }
     * 
     */
    public Terraformingdeliveries createTerraformingdeliveries() {
        return new Terraformingdeliveries();
    }

    /**
     * Create an instance of {@link Terraformingaction }
     * 
     */
    public Terraformingaction createTerraformingaction() {
        return new Terraformingaction();
    }

    /**
     * Create an instance of {@link Basejobquota }
     * 
     */
    public Basejobquota createBasejobquota() {
        return new Basejobquota();
    }

    /**
     * Create an instance of {@link Gamestartjobquota }
     * 
     */
    public Gamestartjobquota createGamestartjobquota() {
        return new Gamestartjobquota();
    }

    /**
     * Create an instance of {@link Gamestartjobquotas }
     * 
     */
    public Gamestartjobquotas createGamestartjobquotas() {
        return new Gamestartjobquotas();
    }

    /**
     * Create an instance of {@link Basegodquota }
     * 
     */
    public Basegodquota createBasegodquota() {
        return new Basegodquota();
    }

    /**
     * Create an instance of {@link Gamestartgodquota }
     * 
     */
    public Gamestartgodquota createGamestartgodquota() {
        return new Gamestartgodquota();
    }

    /**
     * Create an instance of {@link Gamestartgodquotas }
     * 
     */
    public Gamestartgodquotas createGamestartgodquotas() {
        return new Gamestartgodquotas();
    }

    /**
     * Create an instance of {@link Worldshaderparams.Shaderparam.Param }
     * 
     */
    public Worldshaderparams.Shaderparam.Param createWorldshaderparamsShaderparamParam() {
        return new Worldshaderparams.Shaderparam.Param();
    }

    /**
     * Create an instance of {@link Godlocationfilters.Corerange }
     * 
     */
    public Godlocationfilters.Corerange createGodlocationfiltersCorerange() {
        return new Godlocationfilters.Corerange();
    }

    /**
     * Create an instance of {@link Godlocationfilters.Economy }
     * 
     */
    public Godlocationfilters.Economy createGodlocationfiltersEconomy() {
        return new Godlocationfilters.Economy();
    }

    /**
     * Create an instance of {@link Godlocationfilters.Region }
     * 
     */
    public Godlocationfilters.Region createGodlocationfiltersRegion() {
        return new Godlocationfilters.Region();
    }

    /**
     * Create an instance of {@link Godlocationfilters.Security }
     * 
     */
    public Godlocationfilters.Security createGodlocationfiltersSecurity() {
        return new Godlocationfilters.Security();
    }

    /**
     * Create an instance of {@link Godlocationfilters.Sunlight }
     * 
     */
    public Godlocationfilters.Sunlight createGodlocationfiltersSunlight() {
        return new Godlocationfilters.Sunlight();
    }

    /**
     * Create an instance of {@link Positionrange.Distance }
     * 
     */
    public Positionrange.Distance createPositionrangeDistance() {
        return new Positionrange.Distance();
    }

    /**
     * Create an instance of {@link Task.Param }
     * 
     */
    public Task.Param createTaskParam() {
        return new Task.Param();
    }

    /**
     * Create an instance of {@link Joborder.Param }
     * 
     */
    public Joborder.Param createJoborderParam() {
        return new Joborder.Param();
    }

    /**
     * Create an instance of {@link Terraformingpredecessors.Predecessor }
     * 
     */
    public Terraformingpredecessors.Predecessor createTerraformingpredecessorsPredecessor() {
        return new Terraformingpredecessors.Predecessor();
    }

    /**
     * Create an instance of {@link Terraformingremovedprojects.Project }
     * 
     */
    public Terraformingremovedprojects.Project createTerraformingremovedprojectsProject() {
        return new Terraformingremovedprojects.Project();
    }

    /**
     * Create an instance of {@link Propdbcategory.Security }
     * 
     */
    public Propdbcategory.Security createPropdbcategorySecurity() {
        return new Propdbcategory.Security();
    }

    /**
     * Create an instance of {@link Propdbcategory.Economy }
     * 
     */
    public Propdbcategory.Economy createPropdbcategoryEconomy() {
        return new Propdbcategory.Economy();
    }

    /**
     * Create an instance of {@link Propdbcategory.Maintenance }
     * 
     */
    public Propdbcategory.Maintenance createPropdbcategoryMaintenance() {
        return new Propdbcategory.Maintenance();
    }

    /**
     * Create an instance of {@link Selectrandom.Select }
     * 
     */
    public Selectrandom.Select createSelectrandomSelect() {
        return new Selectrandom.Select();
    }

    /**
     * Create an instance of {@link Matchtrade.Offeramount }
     * 
     */
    public Matchtrade.Offeramount createMatchtradeOfferamount() {
        return new Matchtrade.Offeramount();
    }

    /**
     * Create an instance of {@link Matchwaresorcargo.Ware }
     * 
     */
    public Matchwaresorcargo.Ware createMatchwaresorcargoWare() {
        return new Matchwaresorcargo.Ware();
    }

    /**
     * Create an instance of {@link Matchbase.MatchAttention }
     * 
     */
    public Matchbase.MatchAttention createMatchbaseMatchAttention() {
        return new Matchbase.MatchAttention();
    }

    /**
     * Create an instance of {@link Matchbase.MatchPilot }
     * 
     */
    public Matchbase.MatchPilot createMatchbaseMatchPilot() {
        return new Matchbase.MatchPilot();
    }

    /**
     * Create an instance of {@link Matchbase.MatchDistance }
     * 
     */
    public Matchbase.MatchDistance createMatchbaseMatchDistance() {
        return new Matchbase.MatchDistance();
    }

    /**
     * Create an instance of {@link Matchbase.MatchUseBlacklist }
     * 
     */
    public Matchbase.MatchUseBlacklist createMatchbaseMatchUseBlacklist() {
        return new Matchbase.MatchUseBlacklist();
    }

    /**
     * Create an instance of {@link Matchbase.MatchSize }
     * 
     */
    public Matchbase.MatchSize createMatchbaseMatchSize() {
        return new Matchbase.MatchSize();
    }

    /**
     * Create an instance of {@link Matchbase.MatchIsInViewOf }
     * 
     */
    public Matchbase.MatchIsInViewOf createMatchbaseMatchIsInViewOf() {
        return new Matchbase.MatchIsInViewOf();
    }

    /**
     * Create an instance of {@link Matchbase.MatchRelationOf }
     * 
     */
    public Matchbase.MatchRelationOf createMatchbaseMatchRelationOf() {
        return new Matchbase.MatchRelationOf();
    }

    /**
     * Create an instance of {@link Matchbase.MatchRelationTo }
     * 
     */
    public Matchbase.MatchRelationTo createMatchbaseMatchRelationTo() {
        return new Matchbase.MatchRelationTo();
    }

    /**
     * Create an instance of {@link Matchbase.MatchRequiresLicence }
     * 
     */
    public Matchbase.MatchRequiresLicence createMatchbaseMatchRequiresLicence() {
        return new Matchbase.MatchRequiresLicence();
    }

    /**
     * Create an instance of {@link Matchbase.MatchDock }
     * 
     */
    public Matchbase.MatchDock createMatchbaseMatchDock() {
        return new Matchbase.MatchDock();
    }

    /**
     * Create an instance of {@link Matchbase.MatchGateDistance.Blacklist }
     * 
     */
    public Matchbase.MatchGateDistance.Blacklist createMatchbaseMatchGateDistanceBlacklist() {
        return new Matchbase.MatchGateDistance.Blacklist();
    }

    /**
     * Create an instance of {@link Filedoc.Author }
     * 
     */
    public Filedoc.Author createFiledocAuthor() {
        return new Filedoc.Author();
    }

    /**
     * Create an instance of {@link Filedoc.Content }
     * 
     */
    public Filedoc.Content createFiledocContent() {
        return new Filedoc.Content();
    }

    /**
     * Create an instance of {@link Filedoc.Version }
     * 
     */
    public Filedoc.Version createFiledocVersion() {
        return new Filedoc.Version();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Boundaries }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Boundaries createDefaultsDatasetPropertiesBoundaries() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Boundaries();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Identification }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Identification createDefaultsDatasetPropertiesIdentification() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Identification();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Area }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Area createDefaultsDatasetPropertiesArea() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Area();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Backgroundcolor }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Backgroundcolor createDefaultsDatasetPropertiesBackgroundcolor() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Backgroundcolor();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds.World }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds.World createDefaultsDatasetPropertiesWorldsWorld() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Worlds.World();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Space }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Space createDefaultsDatasetPropertiesSystemSpace() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Space();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons.Moon }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons.Moon createDefaultsDatasetPropertiesSystemPlanetsPlanetMoonsMoon() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Planets.Planet.Moons.Moon();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns.Sun }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns.Sun createDefaultsDatasetPropertiesSystemSunsSun() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.System.Suns.Sun();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Music }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Music createDefaultsDatasetPropertiesSoundsMusic() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Music();
    }

    /**
     * Create an instance of {@link be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Fightmusic }
     * 
     */
    public be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Fightmusic createDefaultsDatasetPropertiesSoundsFightmusic() {
        return new be.celludriel.universegenerator.model.xml.libraries.Defaults.Dataset.Properties.Sounds.Fightmusic();
    }

    /**
     * Create an instance of {@link God.Products.Product.Category }
     * 
     */
    public God.Products.Product.Category createGodProductsProductCategory() {
        return new God.Products.Product.Category();
    }

    /**
     * Create an instance of {@link God.Products.Product.Module.Compatibilities.Limits }
     * 
     */
    public God.Products.Product.Module.Compatibilities.Limits createGodProductsProductModuleCompatibilitiesLimits() {
        return new God.Products.Product.Module.Compatibilities.Limits();
    }

    /**
     * Create an instance of {@link God.Products.Product.Module.Compatibilities.Production }
     * 
     */
    public God.Products.Product.Module.Compatibilities.Production createGodProductsProductModuleCompatibilitiesProduction() {
        return new God.Products.Product.Module.Compatibilities.Production();
    }

    /**
     * Create an instance of {@link God.Stations.Station.StationElement.Name }
     * 
     */
    public God.Stations.Station.StationElement.Name createGodStationsStationStationName() {
        return new God.Stations.Station.StationElement.Name();
    }

    /**
     * Create an instance of {@link God.Stations.Station.StationElement.Loadout.Level }
     * 
     */
    public God.Stations.Station.StationElement.Loadout.Level createGodStationsStationStationLoadoutLevel() {
        return new God.Stations.Station.StationElement.Loadout.Level();
    }

    /**
     * Create an instance of {@link God.Stations.Station.StationElement.Loadout.Variation }
     * 
     */
    public God.Stations.Station.StationElement.Loadout.Variation createGodStationsStationStationLoadoutVariation() {
        return new God.Stations.Station.StationElement.Loadout.Variation();
    }

    /**
     * Create an instance of {@link God.Stations.Defaults.Modules }
     * 
     */
    public God.Stations.Defaults.Modules createGodStationsDefaultsModules() {
        return new God.Stations.Defaults.Modules();
    }

    /**
     * Create an instance of {@link God.Stations.Defaults.Location.Corerange }
     * 
     */
    public God.Stations.Defaults.Location.Corerange createGodStationsDefaultsLocationCorerange() {
        return new God.Stations.Defaults.Location.Corerange();
    }

    /**
     * Create an instance of {@link God.Objects.Object.ObjectElement.Name }
     * 
     */
    public God.Objects.Object.ObjectElement.Name createGodObjectsObjectObjectName() {
        return new God.Objects.Object.ObjectElement.Name();
    }

    /**
     * Create an instance of {@link Jobs.Job.Basket }
     * 
     */
    public Jobs.Job.Basket createJobsJobBasket() {
        return new Jobs.Job.Basket();
    }

    /**
     * Create an instance of {@link Jobs.Job.Category }
     * 
     */
    public Jobs.Job.Category createJobsJobCategory() {
        return new Jobs.Job.Category();
    }

    /**
     * Create an instance of {@link Jobs.Job.Orders }
     * 
     */
    public Jobs.Job.Orders createJobsJobOrders() {
        return new Jobs.Job.Orders();
    }

    /**
     * Create an instance of {@link Jobs.Job.Tasks }
     * 
     */
    public Jobs.Job.Tasks createJobsJobTasks() {
        return new Jobs.Job.Tasks();
    }

    /**
     * Create an instance of {@link Jobs.Job.Commander }
     * 
     */
    public Jobs.Job.Commander createJobsJobCommander() {
        return new Jobs.Job.Commander();
    }

    /**
     * Create an instance of {@link Jobs.Job.Encounters }
     * 
     */
    public Jobs.Job.Encounters createJobsJobEncounters() {
        return new Jobs.Job.Encounters();
    }

    /**
     * Create an instance of {@link Jobs.Job.Environment }
     * 
     */
    public Jobs.Job.Environment createJobsJobEnvironment() {
        return new Jobs.Job.Environment();
    }

    /**
     * Create an instance of {@link Jobs.Job.Modifiers }
     * 
     */
    public Jobs.Job.Modifiers createJobsJobModifiers() {
        return new Jobs.Job.Modifiers();
    }

    /**
     * Create an instance of {@link Jobs.Job.Time }
     * 
     */
    public Jobs.Job.Time createJobsJobTime() {
        return new Jobs.Job.Time();
    }

    /**
     * Create an instance of {@link Jobs.Job.Expirationtime }
     * 
     */
    public Jobs.Job.Expirationtime createJobsJobExpirationtime() {
        return new Jobs.Job.Expirationtime();
    }

    /**
     * Create an instance of {@link Jobs.Job.Ship }
     * 
     */
    public Jobs.Job.Ship createJobsJobShip() {
        return new Jobs.Job.Ship();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Owner }
     * 
     */
    public Jobs.Job.Masstraffic.Owner createJobsJobMasstrafficOwner() {
        return new Jobs.Job.Masstraffic.Owner();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Pilot }
     * 
     */
    public Jobs.Job.Masstraffic.Pilot createJobsJobMasstrafficPilot() {
        return new Jobs.Job.Masstraffic.Pilot();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Paint }
     * 
     */
    public Jobs.Job.Masstraffic.Paint createJobsJobMasstrafficPaint() {
        return new Jobs.Job.Masstraffic.Paint();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Basket }
     * 
     */
    public Jobs.Job.Masstraffic.Basket createJobsJobMasstrafficBasket() {
        return new Jobs.Job.Masstraffic.Basket();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Drop }
     * 
     */
    public Jobs.Job.Masstraffic.Drop createJobsJobMasstrafficDrop() {
        return new Jobs.Job.Masstraffic.Drop();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Fillpercent }
     * 
     */
    public Jobs.Job.Masstraffic.People.Fillpercent createJobsJobMasstrafficPeopleFillpercent() {
        return new Jobs.Job.Masstraffic.People.Fillpercent();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Name }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Name createJobsJobMasstrafficPeoplePersonName() {
        return new Jobs.Job.Masstraffic.People.Person.Name();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Page }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Page createJobsJobMasstrafficPeoplePersonPage() {
        return new Jobs.Job.Masstraffic.People.Person.Page();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Stock }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Stock createJobsJobMasstrafficPeoplePersonStock() {
        return new Jobs.Job.Masstraffic.People.Person.Stock();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Clothing }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Clothing createJobsJobMasstrafficPeoplePersonClothing() {
        return new Jobs.Job.Masstraffic.People.Person.Clothing();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.People.Person.Skills.Skill }
     * 
     */
    public Jobs.Job.Masstraffic.People.Person.Skills.Skill createJobsJobMasstrafficPeoplePersonSkillsSkill() {
        return new Jobs.Job.Masstraffic.People.Person.Skills.Skill();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Units.Unit }
     * 
     */
    public Jobs.Job.Masstraffic.Units.Unit createJobsJobMasstrafficUnitsUnit() {
        return new Jobs.Job.Masstraffic.Units.Unit();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Inventory.Wares.Fillamount }
     * 
     */
    public Jobs.Job.Masstraffic.Inventory.Wares.Fillamount createJobsJobMasstrafficInventoryWaresFillamount() {
        return new Jobs.Job.Masstraffic.Inventory.Wares.Fillamount();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Inventory.Wares.Fillvalue }
     * 
     */
    public Jobs.Job.Masstraffic.Inventory.Wares.Fillvalue createJobsJobMasstrafficInventoryWaresFillvalue() {
        return new Jobs.Job.Masstraffic.Inventory.Wares.Fillvalue();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Cargo.Wares.Fillpercent }
     * 
     */
    public Jobs.Job.Masstraffic.Cargo.Wares.Fillpercent createJobsJobMasstrafficCargoWaresFillpercent() {
        return new Jobs.Job.Masstraffic.Cargo.Wares.Fillpercent();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Cargo.Wares.Fillvalue }
     * 
     */
    public Jobs.Job.Masstraffic.Cargo.Wares.Fillvalue createJobsJobMasstrafficCargoWaresFillvalue() {
        return new Jobs.Job.Masstraffic.Cargo.Wares.Fillvalue();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Ammo.Macro.Fillpercent }
     * 
     */
    public Jobs.Job.Masstraffic.Ammo.Macro.Fillpercent createJobsJobMasstrafficAmmoMacroFillpercent() {
        return new Jobs.Job.Masstraffic.Ammo.Macro.Fillpercent();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Ammo.Macro.Fillamount }
     * 
     */
    public Jobs.Job.Masstraffic.Ammo.Macro.Fillamount createJobsJobMasstrafficAmmoMacroFillamount() {
        return new Jobs.Job.Masstraffic.Ammo.Macro.Fillamount();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Chance }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Chance createJobsJobMasstrafficEquipmentmodsChance() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Chance();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Engine }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Engine createJobsJobMasstrafficEquipmentmodsEngine() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Engine();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Weapon }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Weapon createJobsJobMasstrafficEquipmentmodsWeapon() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Weapon();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Shield }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Shield createJobsJobMasstrafficEquipmentmodsShield() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Shield();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Ship }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Ship createJobsJobMasstrafficEquipmentmodsShip() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Ship();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Equipmentmods.Mods }
     * 
     */
    public Jobs.Job.Masstraffic.Equipmentmods.Mods createJobsJobMasstrafficEquipmentmodsMods() {
        return new Jobs.Job.Masstraffic.Equipmentmods.Mods();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Loadout.Level }
     * 
     */
    public Jobs.Job.Masstraffic.Loadout.Level createJobsJobMasstrafficLoadoutLevel() {
        return new Jobs.Job.Masstraffic.Loadout.Level();
    }

    /**
     * Create an instance of {@link Jobs.Job.Masstraffic.Loadout.Variation }
     * 
     */
    public Jobs.Job.Masstraffic.Loadout.Variation createJobsJobMasstrafficLoadoutVariation() {
        return new Jobs.Job.Masstraffic.Loadout.Variation();
    }

    /**
     * Create an instance of {@link Jobs.Job.Subordinates.Subordinate }
     * 
     */
    public Jobs.Job.Subordinates.Subordinate createJobsJobSubordinatesSubordinate() {
        return new Jobs.Job.Subordinates.Subordinate();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Economy }
     * 
     */
    public Jobs.Job.Location.Economy createJobsJobLocationEconomy() {
        return new Jobs.Job.Location.Economy();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Security }
     * 
     */
    public Jobs.Job.Location.Security createJobsJobLocationSecurity() {
        return new Jobs.Job.Location.Security();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Sunlight }
     * 
     */
    public Jobs.Job.Location.Sunlight createJobsJobLocationSunlight() {
        return new Jobs.Job.Location.Sunlight();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factionlicences.Factionlicence }
     * 
     */
    public Jobs.Job.Location.Factionlicences.Factionlicence createJobsJobLocationFactionlicencesFactionlicence() {
        return new Jobs.Job.Location.Factionlicences.Factionlicence();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factionraces.Factionrace }
     * 
     */
    public Jobs.Job.Location.Factionraces.Factionrace createJobsJobLocationFactionracesFactionrace() {
        return new Jobs.Job.Location.Factionraces.Factionrace();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Policefaction.PolicefactionElement }
     * 
     */
    public Jobs.Job.Location.Policefaction.PolicefactionElement createJobsJobLocationPolicefactionPolicefaction() {
        return new Jobs.Job.Location.Policefaction.PolicefactionElement();
    }

    /**
     * Create an instance of {@link Jobs.Job.Location.Factions.Faction }
     * 
     */
    public Jobs.Job.Location.Factions.Faction createJobsJobLocationFactionsFaction() {
        return new Jobs.Job.Location.Factions.Faction();
    }

    /**
     * Create an instance of {@link Modulesets.Set.Race }
     * 
     */
    public Modulesets.Set.Race createModulesetsSetRace() {
        return new Modulesets.Set.Race();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "amount", scope = Matchtradeoffervalues.class)
    public JAXBElement<Range> createMatchtradeoffervaluesAmount(Range value) {
        return new JAXBElement<Range>(_MatchtradeoffervaluesAmount_QNAME, Range.class, Matchtradeoffervalues.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "minamount", scope = Matchtradeoffervalues.class)
    public JAXBElement<Range> createMatchtradeoffervaluesMinamount(Range value) {
        return new JAXBElement<Range>(_MatchtradeoffervaluesMinamount_QNAME, Range.class, Matchtradeoffervalues.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "totalprice", scope = Matchtradeoffervalues.class)
    public JAXBElement<Range> createMatchtradeoffervaluesTotalprice(Range value) {
        return new JAXBElement<Range>(_MatchtradeoffervaluesTotalprice_QNAME, Range.class, Matchtradeoffervalues.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Range }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "minprice", scope = Matchtradeoffervalues.class)
    public JAXBElement<Range> createMatchtradeoffervaluesMinprice(Range value) {
        return new JAXBElement<Range>(_MatchtradeoffervaluesMinprice_QNAME, Range.class, Matchtradeoffervalues.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match", scope = Matchbase.class)
    public JAXBElement<Matchsubfilter> createMatchbaseMatch(Matchsubfilter value) {
        return new JAXBElement<Matchsubfilter>(_MatchbaseMatch_QNAME, Matchsubfilter.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_any", scope = Matchbase.class)
    public JAXBElement<Matchsubfilter> createMatchbaseMatchAny(Matchsubfilter value) {
        return new JAXBElement<Matchsubfilter>(_MatchbaseMatchAny_QNAME, Matchsubfilter.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_parent", scope = Matchbase.class)
    public JAXBElement<Matchsubfilter> createMatchbaseMatchParent(Matchsubfilter value) {
        return new JAXBElement<Matchsubfilter>(_MatchbaseMatchParent_QNAME, Matchsubfilter.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilter }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_context", scope = Matchbase.class)
    public JAXBElement<Matchsubfilter> createMatchbaseMatchContext(Matchsubfilter value) {
        return new JAXBElement<Matchsubfilter>(_MatchbaseMatchContext_QNAME, Matchsubfilter.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilterrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilterrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_child", scope = Matchbase.class)
    public JAXBElement<Matchsubfilterrange> createMatchbaseMatchChild(Matchsubfilterrange value) {
        return new JAXBElement<Matchsubfilterrange>(_MatchbaseMatchChild_QNAME, Matchsubfilterrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchsubfilterrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchsubfilterrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_content", scope = Matchbase.class)
    public JAXBElement<Matchsubfilterrange> createMatchbaseMatchContent(Matchsubfilterrange value) {
        return new JAXBElement<Matchsubfilterrange>(_MatchbaseMatchContent_QNAME, Matchsubfilterrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_macro_children", scope = Matchbase.class)
    public JAXBElement<Matchrange> createMatchbaseMatchMacroChildren(Matchrange value) {
        return new JAXBElement<Matchrange>(_MatchbaseMatchMacroChildren_QNAME, Matchrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_hull", scope = Matchbase.class)
    public JAXBElement<Matchrange> createMatchbaseMatchHull(Matchrange value) {
        return new JAXBElement<Matchrange>(_MatchbaseMatchHull_QNAME, Matchrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_max_hull", scope = Matchbase.class)
    public JAXBElement<Matchrange> createMatchbaseMatchMaxHull(Matchrange value) {
        return new JAXBElement<Matchrange>(_MatchbaseMatchMaxHull_QNAME, Matchrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_shield", scope = Matchbase.class)
    public JAXBElement<Matchrange> createMatchbaseMatchShield(Matchrange value) {
        return new JAXBElement<Matchrange>(_MatchbaseMatchShield_QNAME, Matchrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrange }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_secrecy_level", scope = Matchbase.class)
    public JAXBElement<Matchrange> createMatchbaseMatchSecrecyLevel(Matchrange value) {
        return new JAXBElement<Matchrange>(_MatchbaseMatchSecrecyLevel_QNAME, Matchrange.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchAttention }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchAttention }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_attention", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchAttention> createMatchbaseMatchAttention(Matchbase.MatchAttention value) {
        return new JAXBElement<Matchbase.MatchAttention>(_MatchbaseMatchAttention_QNAME, Matchbase.MatchAttention.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchrevealedpercentage }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchrevealedpercentage }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_revealed_percentage", scope = Matchbase.class)
    public JAXBElement<Matchrevealedpercentage> createMatchbaseMatchRevealedPercentage(Matchrevealedpercentage value) {
        return new JAXBElement<Matchrevealedpercentage>(_MatchbaseMatchRevealedPercentage_QNAME, Matchrevealedpercentage.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchPilot }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchPilot }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_pilot", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchPilot> createMatchbaseMatchPilot(Matchbase.MatchPilot value) {
        return new JAXBElement<Matchbase.MatchPilot>(_MatchbaseMatchPilot_QNAME, Matchbase.MatchPilot.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchDistance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchDistance }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_distance", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchDistance> createMatchbaseMatchDistance(Matchbase.MatchDistance value) {
        return new JAXBElement<Matchbase.MatchDistance>(_MatchbaseMatchDistance_QNAME, Matchbase.MatchDistance.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchGateDistance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchGateDistance }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_gate_distance", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchGateDistance> createMatchbaseMatchGateDistance(Matchbase.MatchGateDistance value) {
        return new JAXBElement<Matchbase.MatchGateDistance>(_MatchbaseMatchGateDistance_QNAME, Matchbase.MatchGateDistance.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchUseBlacklist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchUseBlacklist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_use_blacklist", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchUseBlacklist> createMatchbaseMatchUseBlacklist(Matchbase.MatchUseBlacklist value) {
        return new JAXBElement<Matchbase.MatchUseBlacklist>(_MatchbaseMatchUseBlacklist_QNAME, Matchbase.MatchUseBlacklist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchSize }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchSize }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_size", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchSize> createMatchbaseMatchSize(Matchbase.MatchSize value) {
        return new JAXBElement<Matchbase.MatchSize>(_MatchbaseMatchSize_QNAME, Matchbase.MatchSize.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchIsInViewOf }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchIsInViewOf }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_is_in_view_of", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchIsInViewOf> createMatchbaseMatchIsInViewOf(Matchbase.MatchIsInViewOf value) {
        return new JAXBElement<Matchbase.MatchIsInViewOf>(_MatchbaseMatchIsInViewOf_QNAME, Matchbase.MatchIsInViewOf.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchtradeoffer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchtradeoffer }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_buyoffer", scope = Matchbase.class)
    public JAXBElement<Matchtradeoffer> createMatchbaseMatchBuyoffer(Matchtradeoffer value) {
        return new JAXBElement<Matchtradeoffer>(_MatchbaseMatchBuyoffer_QNAME, Matchtradeoffer.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchtradeoffer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchtradeoffer }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_selloffer", scope = Matchbase.class)
    public JAXBElement<Matchtradeoffer> createMatchbaseMatchSelloffer(Matchtradeoffer value) {
        return new JAXBElement<Matchtradeoffer>(_MatchbaseMatchSelloffer_QNAME, Matchtradeoffer.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbuild }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbuild }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_build", scope = Matchbase.class)
    public JAXBElement<Matchbuild> createMatchbaseMatchBuild(Matchbuild value) {
        return new JAXBElement<Matchbuild>(_MatchbaseMatchBuild_QNAME, Matchbuild.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_products", scope = Matchbase.class)
    public JAXBElement<Matchwarelist> createMatchbaseMatchProducts(Matchwarelist value) {
        return new JAXBElement<Matchwarelist>(_MatchbaseMatchProducts_QNAME, Matchwarelist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_resources", scope = Matchbase.class)
    public JAXBElement<Matchwarelist> createMatchbaseMatchResources(Matchwarelist value) {
        return new JAXBElement<Matchwarelist>(_MatchbaseMatchResources_QNAME, Matchwarelist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_any_cargo", scope = Matchbase.class)
    public JAXBElement<Matchwarelist> createMatchbaseMatchAnyCargo(Matchwarelist value) {
        return new JAXBElement<Matchwarelist>(_MatchbaseMatchAnyCargo_QNAME, Matchwarelist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_any_wares", scope = Matchbase.class)
    public JAXBElement<Matchwarelist> createMatchbaseMatchAnyWares(Matchwarelist value) {
        return new JAXBElement<Matchwarelist>(_MatchbaseMatchAnyWares_QNAME, Matchwarelist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwarelist }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_basket_wares", scope = Matchbase.class)
    public JAXBElement<Matchwarelist> createMatchbaseMatchBasketWares(Matchwarelist value) {
        return new JAXBElement<Matchwarelist>(_MatchbaseMatchBasketWares_QNAME, Matchwarelist.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRelationOf }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRelationOf }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_relation_of", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchRelationOf> createMatchbaseMatchRelationOf(Matchbase.MatchRelationOf value) {
        return new JAXBElement<Matchbase.MatchRelationOf>(_MatchbaseMatchRelationOf_QNAME, Matchbase.MatchRelationOf.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRelationTo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRelationTo }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_relation_to", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchRelationTo> createMatchbaseMatchRelationTo(Matchbase.MatchRelationTo value) {
        return new JAXBElement<Matchbase.MatchRelationTo>(_MatchbaseMatchRelationTo_QNAME, Matchbase.MatchRelationTo.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRequiresLicence }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchRequiresLicence }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_requires_licence", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchRequiresLicence> createMatchbaseMatchRequiresLicence(Matchbase.MatchRequiresLicence value) {
        return new JAXBElement<Matchbase.MatchRequiresLicence>(_MatchbaseMatchRequiresLicence_QNAME, Matchbase.MatchRequiresLicence.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchDock }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchbase.MatchDock }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_dock", scope = Matchbase.class)
    public JAXBElement<Matchbase.MatchDock> createMatchbaseMatchDock(Matchbase.MatchDock value) {
        return new JAXBElement<Matchbase.MatchDock>(_MatchbaseMatchDock_QNAME, Matchbase.MatchDock.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_units_stored", scope = Matchbase.class)
    public JAXBElement<Matchunits> createMatchbaseMatchUnitsStored(Matchunits value) {
        return new JAXBElement<Matchunits>(_MatchbaseMatchUnitsStored_QNAME, Matchunits.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_units_available", scope = Matchbase.class)
    public JAXBElement<Matchunits> createMatchbaseMatchUnitsAvailable(Matchunits value) {
        return new JAXBElement<Matchunits>(_MatchbaseMatchUnitsAvailable_QNAME, Matchunits.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchunits }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_units_unavailable", scope = Matchbase.class)
    public JAXBElement<Matchunits> createMatchbaseMatchUnitsUnavailable(Matchunits value) {
        return new JAXBElement<Matchunits>(_MatchbaseMatchUnitsUnavailable_QNAME, Matchunits.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwaresorcargo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwaresorcargo }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_cargo", scope = Matchbase.class)
    public JAXBElement<Matchwaresorcargo> createMatchbaseMatchCargo(Matchwaresorcargo value) {
        return new JAXBElement<Matchwaresorcargo>(_MatchbaseMatchCargo_QNAME, Matchwaresorcargo.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchwaresorcargo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchwaresorcargo }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_wares", scope = Matchbase.class)
    public JAXBElement<Matchwaresorcargo> createMatchbaseMatchWares(Matchwaresorcargo value) {
        return new JAXBElement<Matchwaresorcargo>(_MatchbaseMatchWares_QNAME, Matchwaresorcargo.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchloadout }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchloadout }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_loadout", scope = Matchbase.class)
    public JAXBElement<Matchloadout> createMatchbaseMatchLoadout(Matchloadout value) {
        return new JAXBElement<Matchloadout>(_MatchbaseMatchLoadout_QNAME, Matchloadout.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchweaponmod }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchweaponmod }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_weapon_mod", scope = Matchbase.class)
    public JAXBElement<Matchweaponmod> createMatchbaseMatchWeaponMod(Matchweaponmod value) {
        return new JAXBElement<Matchweaponmod>(_MatchbaseMatchWeaponMod_QNAME, Matchweaponmod.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchenginemod }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchenginemod }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_engine_mod", scope = Matchbase.class)
    public JAXBElement<Matchenginemod> createMatchbaseMatchEngineMod(Matchenginemod value) {
        return new JAXBElement<Matchenginemod>(_MatchbaseMatchEngineMod_QNAME, Matchenginemod.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchshieldmod }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchshieldmod }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_shield_mod", scope = Matchbase.class)
    public JAXBElement<Matchshieldmod> createMatchbaseMatchShieldMod(Matchshieldmod value) {
        return new JAXBElement<Matchshieldmod>(_MatchbaseMatchShieldMod_QNAME, Matchshieldmod.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchshipmod }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchshipmod }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_ship_mod", scope = Matchbase.class)
    public JAXBElement<Matchshipmod> createMatchbaseMatchShipMod(Matchshipmod value) {
        return new JAXBElement<Matchshipmod>(_MatchbaseMatchShipMod_QNAME, Matchshipmod.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Matchpaintmod }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Matchpaintmod }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_paint_mod", scope = Matchbase.class)
    public JAXBElement<Matchpaintmod> createMatchbaseMatchPaintMod(Matchpaintmod value) {
        return new JAXBElement<Matchpaintmod>(_MatchbaseMatchPaintMod_QNAME, Matchpaintmod.class, Matchbase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "match_any_equipment_mod", scope = Matchbase.class)
    public JAXBElement<java.lang.Object> createMatchbaseMatchAnyEquipmentMod(java.lang.Object value) {
        return new JAXBElement<java.lang.Object>(_MatchbaseMatchAnyEquipmentMod_QNAME, java.lang.Object.class, Matchbase.class, value);
    }

}
