//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orientationlookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="orientationlookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="align_left"/&gt;
 *     &lt;enumeration value="align_left_bbox"/&gt;
 *     &lt;enumeration value="align_right"/&gt;
 *     &lt;enumeration value="align_right_bbox"/&gt;
 *     &lt;enumeration value="look_at"/&gt;
 *     &lt;enumeration value="look_at_bbox"/&gt;
 *     &lt;enumeration value="look_away"/&gt;
 *     &lt;enumeration value="look_away_bbox"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "orientationlookup")
@XmlEnum
public enum Orientationlookup {


    /**
     * 
     *             Align so that refpos/refobj is on the left side
     *           
     * 
     */
    @XmlEnumValue("align_left")
    ALIGN_LEFT("align_left"),

    /**
     * 
     *             Align so that refobj-bounding-box is on the left side (requires valid refobject!)
     *           
     * 
     */
    @XmlEnumValue("align_left_bbox")
    ALIGN_LEFT_BBOX("align_left_bbox"),

    /**
     * 
     *             Align so that refpos/refobj is on the right side
     *           
     * 
     */
    @XmlEnumValue("align_right")
    ALIGN_RIGHT("align_right"),

    /**
     * 
     *             Align so that refobj-bounding-box is on the right side (requires valid refobject!)
     *           
     * 
     */
    @XmlEnumValue("align_right_bbox")
    ALIGN_RIGHT_BBOX("align_right_bbox"),

    /**
     * 
     *             Orientation that looks directly at refpos/refobj-center
     *           
     * 
     */
    @XmlEnumValue("look_at")
    LOOK_AT("look_at"),

    /**
     * 
     *             Orientation that looks directly at refobj-bounding-box (requires valid refobject!)
     *           
     * 
     */
    @XmlEnumValue("look_at_bbox")
    LOOK_AT_BBOX("look_at_bbox"),

    /**
     * 
     *             Orientation that looks away from refpos/refobj-center
     *           
     * 
     */
    @XmlEnumValue("look_away")
    LOOK_AWAY("look_away"),

    /**
     * 
     *             Orientation that looks away from refobj-bounding-box (requires valid refobject!)
     *           
     * 
     */
    @XmlEnumValue("look_away_bbox")
    LOOK_AWAY_BBOX("look_away_bbox");
    private final String value;

    Orientationlookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Orientationlookup fromValue(String v) {
        for (Orientationlookup c: Orientationlookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
