//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectionlookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="selectionlookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="one"/&gt;
 *     &lt;enumeration value="random"/&gt;
 *     &lt;enumeration value="random_except"/&gt;
 *     &lt;enumeration value="choose"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "selectionlookup")
@XmlEnum
public enum Selectionlookup {


    /**
     * 
     *             One
     *           
     * 
     */
    @XmlEnumValue("one")
    ONE("one"),

    /**
     * 
     *             Random
     *           
     * 
     */
    @XmlEnumValue("random")
    RANDOM("random"),

    /**
     * 
     *             Random, excluding an item that can be optionally specified by code
     *           
     * 
     */
    @XmlEnumValue("random_except")
    RANDOM_EXCEPT("random_except"),

    /**
     * 
     *             Choose
     *           
     * 
     */
    @XmlEnumValue("choose")
    CHOOSE("choose");
    private final String value;

    Selectionlookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Selectionlookup fromValue(String v) {
        for (Selectionlookup c: Selectionlookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
