//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for terraformingaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="terraformingaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="conditions" type="{}terraformingconditions" minOccurs="0"/&gt;
 *         &lt;element name="effects" type="{}terraformingeffects" minOccurs="0"/&gt;
 *         &lt;element name="sideeffects" type="{}terraformingsideeffects" minOccurs="0"/&gt;
 *         &lt;element name="rebates" type="{}terraformingrebates" minOccurs="0"/&gt;
 *         &lt;element name="resources" type="{}terraformingresources" minOccurs="0"/&gt;
 *         &lt;element name="deliveries" type="{}terraformingdeliveries" minOccurs="0"/&gt;
 *         &lt;element name="predecessors" type="{}terraformingpredecessors" minOccurs="0"/&gt;
 *         &lt;element name="removedprojects" type="{}terraformingremovedprojects" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attGroup ref="{}action"/&gt;
 *       &lt;attribute name="cluster" use="required" type="{}cluster" /&gt;
 *       &lt;attribute name="id" use="required" type="{}expression" /&gt;
 *       &lt;attribute name="name" type="{}expression" /&gt;
 *       &lt;attribute name="description" type="{}expression" /&gt;
 *       &lt;attribute name="duration" type="{}expression" /&gt;
 *       &lt;attribute name="repeat" type="{}expression" /&gt;
 *       &lt;attribute name="successchance" type="{}expression" /&gt;
 *       &lt;attribute name="price" type="{}expression" /&gt;
 *       &lt;attribute name="pricescale" type="{}terraformingpricescalelookup" /&gt;
 *       &lt;attribute name="starttime" type="{}expression" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "terraformingaction", propOrder = {

})
public class Terraformingaction {

    protected Terraformingconditions conditions;
    protected Terraformingeffects effects;
    protected Terraformingsideeffects sideeffects;
    protected Terraformingrebates rebates;
    protected Terraformingresources resources;
    protected Terraformingdeliveries deliveries;
    protected Terraformingpredecessors predecessors;
    protected Terraformingremovedprojects removedprojects;
    @XmlAttribute(name = "cluster", required = true)
    protected String cluster;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "duration")
    protected String duration;
    @XmlAttribute(name = "repeat")
    protected String repeat;
    @XmlAttribute(name = "successchance")
    protected String successchance;
    @XmlAttribute(name = "price")
    protected String price;
    @XmlAttribute(name = "pricescale")
    protected Terraformingpricescalelookup pricescale;
    @XmlAttribute(name = "starttime")
    protected String starttime;
    @XmlAttribute(name = "chance")
    protected String chance;
    @XmlAttribute(name = "weight")
    protected String weight;
    @XmlAttribute(name = "comment")
    protected String comment;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingconditions }
     *     
     */
    public Terraformingconditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingconditions }
     *     
     */
    public void setConditions(Terraformingconditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the effects property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingeffects }
     *     
     */
    public Terraformingeffects getEffects() {
        return effects;
    }

    /**
     * Sets the value of the effects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingeffects }
     *     
     */
    public void setEffects(Terraformingeffects value) {
        this.effects = value;
    }

    /**
     * Gets the value of the sideeffects property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingsideeffects }
     *     
     */
    public Terraformingsideeffects getSideeffects() {
        return sideeffects;
    }

    /**
     * Sets the value of the sideeffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingsideeffects }
     *     
     */
    public void setSideeffects(Terraformingsideeffects value) {
        this.sideeffects = value;
    }

    /**
     * Gets the value of the rebates property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingrebates }
     *     
     */
    public Terraformingrebates getRebates() {
        return rebates;
    }

    /**
     * Sets the value of the rebates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingrebates }
     *     
     */
    public void setRebates(Terraformingrebates value) {
        this.rebates = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingresources }
     *     
     */
    public Terraformingresources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingresources }
     *     
     */
    public void setResources(Terraformingresources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the deliveries property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingdeliveries }
     *     
     */
    public Terraformingdeliveries getDeliveries() {
        return deliveries;
    }

    /**
     * Sets the value of the deliveries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingdeliveries }
     *     
     */
    public void setDeliveries(Terraformingdeliveries value) {
        this.deliveries = value;
    }

    /**
     * Gets the value of the predecessors property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingpredecessors }
     *     
     */
    public Terraformingpredecessors getPredecessors() {
        return predecessors;
    }

    /**
     * Sets the value of the predecessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingpredecessors }
     *     
     */
    public void setPredecessors(Terraformingpredecessors value) {
        this.predecessors = value;
    }

    /**
     * Gets the value of the removedprojects property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingremovedprojects }
     *     
     */
    public Terraformingremovedprojects getRemovedprojects() {
        return removedprojects;
    }

    /**
     * Sets the value of the removedprojects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingremovedprojects }
     *     
     */
    public void setRemovedprojects(Terraformingremovedprojects value) {
        this.removedprojects = value;
    }

    /**
     * Gets the value of the cluster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCluster() {
        return cluster;
    }

    /**
     * Sets the value of the cluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCluster(String value) {
        this.cluster = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeat() {
        return repeat;
    }

    /**
     * Sets the value of the repeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeat(String value) {
        this.repeat = value;
    }

    /**
     * Gets the value of the successchance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccesschance() {
        return successchance;
    }

    /**
     * Sets the value of the successchance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccesschance(String value) {
        this.successchance = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the pricescale property.
     * 
     * @return
     *     possible object is
     *     {@link Terraformingpricescalelookup }
     *     
     */
    public Terraformingpricescalelookup getPricescale() {
        return pricescale;
    }

    /**
     * Sets the value of the pricescale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terraformingpricescalelookup }
     *     
     */
    public void setPricescale(Terraformingpricescalelookup value) {
        this.pricescale = value;
    }

    /**
     * Gets the value of the starttime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStarttime(String value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the chance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChance() {
        return chance;
    }

    /**
     * Sets the value of the chance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChance(String value) {
        this.chance = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
