//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tradesorterlookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tradesorterlookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="amount"/&gt;
 *     &lt;enumeration value="distance"/&gt;
 *     &lt;enumeration value="name"/&gt;
 *     &lt;enumeration value="offeramount"/&gt;
 *     &lt;enumeration value="price"/&gt;
 *     &lt;enumeration value="relativeprice"/&gt;
 *     &lt;enumeration value="stocklevel"/&gt;
 *     &lt;enumeration value="totalprice"/&gt;
 *     &lt;enumeration value="totalvolume"/&gt;
 *     &lt;enumeration value="volume"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tradesorterlookup")
@XmlEnum
public enum Tradesorterlookup {

    @XmlEnumValue("amount")
    AMOUNT("amount"),
    @XmlEnumValue("distance")
    DISTANCE("distance"),
    @XmlEnumValue("name")
    NAME("name"),
    @XmlEnumValue("offeramount")
    OFFERAMOUNT("offeramount"),
    @XmlEnumValue("price")
    PRICE("price"),
    @XmlEnumValue("relativeprice")
    RELATIVEPRICE("relativeprice"),
    @XmlEnumValue("stocklevel")
    STOCKLEVEL("stocklevel"),
    @XmlEnumValue("totalprice")
    TOTALPRICE("totalprice"),
    @XmlEnumValue("totalvolume")
    TOTALVOLUME("totalvolume"),
    @XmlEnumValue("volume")
    VOLUME("volume");
    private final String value;

    Tradesorterlookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Tradesorterlookup fromValue(String v) {
        for (Tradesorterlookup c: Tradesorterlookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
