//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.01 at 12:27:02 AM CEST 
//


package be.celludriel.universegenerator.model.xml.libraries;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for weapontypelookup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="weapontypelookup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="all"/&gt;
 *     &lt;enumeration value="combat"/&gt;
 *     &lt;enumeration value="mining"/&gt;
 *     &lt;enumeration value="repair"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "weapontypelookup")
@XmlEnum
public enum Weapontypelookup {


    /**
     * 
     *             All weapons (including mining or repair lasers!)
     *           
     * 
     */
    @XmlEnumValue("all")
    ALL("all"),

    /**
     * 
     *             Combat weapons (default)
     *           
     * 
     */
    @XmlEnumValue("combat")
    COMBAT("combat"),

    /**
     * 
     *             Mining weapons
     *           
     * 
     */
    @XmlEnumValue("mining")
    MINING("mining"),

    /**
     * 
     *             Repair weapons
     *           
     * 
     */
    @XmlEnumValue("repair")
    REPAIR("repair");
    private final String value;

    Weapontypelookup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Weapontypelookup fromValue(String v) {
        for (Weapontypelookup c: Weapontypelookup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
